
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  emailVerifiedAt: 'emailVerifiedAt',
  passwordHash: 'passwordHash',
  name: 'name',
  locale: 'locale',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  tokenHash: 'tokenHash',
  userAgent: 'userAgent',
  ipHash: 'ipHash',
  expiresAt: 'expiresAt',
  revokedAt: 'revokedAt',
  createdAt: 'createdAt'
};

exports.Prisma.MagicLinkTokenScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  tokenHash: 'tokenHash',
  expiresAt: 'expiresAt',
  usedAt: 'usedAt',
  createdAt: 'createdAt'
};

exports.Prisma.CardTemplateScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  name: 'name',
  sectorHint: 'sectorHint',
  componentKey: 'componentKey',
  previewPath: 'previewPath',
  oneTimeCents: 'oneTimeCents',
  monthlyCents: 'monthlyCents',
  yearlyCents: 'yearlyCents',
  stripeOneTimePriceId: 'stripeOneTimePriceId',
  stripeMonthlyPriceId: 'stripeMonthlyPriceId',
  stripeYearlyPriceId: 'stripeYearlyPriceId',
  isActive: 'isActive',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CardOrderScalarFieldEnum = {
  id: 'id',
  orderNumber: 'orderNumber',
  slug: 'slug',
  templateId: 'templateId',
  userId: 'userId',
  contactName: 'contactName',
  contactEmail: 'contactEmail',
  contactPhone: 'contactPhone',
  callMeBack: 'callMeBack',
  cardData: 'cardData',
  brandPrimaryHex: 'brandPrimaryHex',
  brandAccentHex: 'brandAccentHex',
  photoPath: 'photoPath',
  logoPath: 'logoPath',
  qrStyle: 'qrStyle',
  videoUrl: 'videoUrl',
  conciergeAddon: 'conciergeAddon',
  layoutKey: 'layoutKey',
  themeKey: 'themeKey',
  customBlocks: 'customBlocks',
  billingMode: 'billingMode',
  amountCents: 'amountCents',
  currency: 'currency',
  locale: 'locale',
  stripeSessionId: 'stripeSessionId',
  stripePaymentIntentId: 'stripePaymentIntentId',
  stripeSubscriptionId: 'stripeSubscriptionId',
  stripeCustomerId: 'stripeCustomerId',
  status: 'status',
  designNotes: 'designNotes',
  editToken: 'editToken',
  desiredSlug: 'desiredSlug',
  slugHistory: 'slugHistory',
  contactedAt: 'contactedAt',
  contactedByNote: 'contactedByNote',
  paidAt: 'paidAt',
  awaitingDesignAt: 'awaitingDesignAt',
  publishedAt: 'publishedAt',
  customDomain: 'customDomain',
  customDomainVerified: 'customDomainVerified',
  customDomainVerifiedAt: 'customDomainVerifiedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SubscriptionScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  stripeSubscriptionId: 'stripeSubscriptionId',
  status: 'status',
  currentPeriodEnd: 'currentPeriodEnd',
  cancelAt: 'cancelAt',
  canceledAt: 'canceledAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CardViewScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  source: 'source',
  ua: 'ua',
  country: 'country',
  city: 'city',
  referer: 'referer',
  createdAt: 'createdAt'
};

exports.Prisma.CardLeadScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  name: 'name',
  email: 'email',
  phone: 'phone',
  message: 'message',
  interest: 'interest',
  meetingContext: 'meetingContext',
  company: 'company',
  ownerNotes: 'ownerNotes',
  tags: 'tags',
  status: 'status',
  priority: 'priority',
  lastContactedAt: 'lastContactedAt',
  createdAt: 'createdAt'
};

exports.Prisma.CardLinkScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  code: 'code',
  label: 'label',
  source: 'source',
  campaign: 'campaign',
  medium: 'medium',
  eventName: 'eventName',
  destinationUrl: 'destinationUrl',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ScanEventScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  linkId: 'linkId',
  source: 'source',
  campaign: 'campaign',
  eventName: 'eventName',
  referer: 'referer',
  userAgent: 'userAgent',
  deviceType: 'deviceType',
  ipHash: 'ipHash',
  createdAt: 'createdAt'
};

exports.Prisma.CardConnectionScalarFieldEnum = {
  id: 'id',
  ownerCardId: 'ownerCardId',
  visitorCardId: 'visitorCardId',
  source: 'source',
  campaign: 'campaign',
  eventName: 'eventName',
  note: 'note',
  status: 'status',
  tags: 'tags',
  priority: 'priority',
  lastContactedAt: 'lastContactedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CardAlbumPhotoScalarFieldEnum = {
  id: 'id',
  cardOrderId: 'cardOrderId',
  uploaderType: 'uploaderType',
  uploaderName: 'uploaderName',
  uploaderIpHash: 'uploaderIpHash',
  photoPath: 'photoPath',
  caption: 'caption',
  connectionId: 'connectionId',
  status: 'status',
  createdAt: 'createdAt',
  approvedAt: 'approvedAt'
};

exports.Prisma.CardWebhookScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  url: 'url',
  secret: 'secret',
  events: 'events',
  active: 'active',
  lastDeliveryAt: 'lastDeliveryAt',
  lastDeliveryStatus: 'lastDeliveryStatus',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrderStatusHistoryScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  fromStatus: 'fromStatus',
  toStatus: 'toStatus',
  note: 'note',
  actor: 'actor',
  createdAt: 'createdAt'
};

exports.Prisma.VoiceBillingPlanScalarFieldEnum = {
  id: 'id',
  planKey: 'planKey',
  displayName: 'displayName',
  monthlyMinutes: 'monthlyMinutes',
  overageRateCents: 'overageRateCents',
  monthlyCents: 'monthlyCents',
  yearlyCents: 'yearlyCents',
  features: 'features',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VoiceTenantScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  businessName: 'businessName',
  contactEmail: 'contactEmail',
  contactPhone: 'contactPhone',
  timezone: 'timezone',
  locale: 'locale',
  mode: 'mode',
  status: 'status',
  planId: 'planId',
  tenantToken: 'tenantToken',
  webhookSecret: 'webhookSecret',
  apiToken: 'apiToken',
  providerName: 'providerName',
  providerAccountId: 'providerAccountId',
  businessDescription: 'businessDescription',
  businessAddress: 'businessAddress',
  businessCategory: 'businessCategory',
  kutasiaOrderId: 'kutasiaOrderId',
  featureFlags: 'featureFlags',
  trialEndsAt: 'trialEndsAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VoiceAgentScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  name: 'name',
  displayName: 'displayName',
  language: 'language',
  voiceId: 'voiceId',
  status: 'status',
  promptTemplate: 'promptTemplate',
  systemPrompt: 'systemPrompt',
  providerAgentId: 'providerAgentId',
  maxDurationSeconds: 'maxDurationSeconds',
  interruptionSensitivity: 'interruptionSensitivity',
  responseDelayMs: 'responseDelayMs',
  endCallPhrases: 'endCallPhrases',
  dtmfHandoffDigit: 'dtmfHandoffDigit',
  ambientSoundEnabled: 'ambientSoundEnabled',
  providerOverrides: 'providerOverrides',
  lastSyncedAt: 'lastSyncedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VoicePhoneNumberScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  agentId: 'agentId',
  e164Number: 'e164Number',
  friendlyName: 'friendlyName',
  providerPhoneId: 'providerPhoneId',
  status: 'status',
  country: 'country',
  importedAt: 'importedAt',
  releasedAt: 'releasedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VoiceCallScalarFieldEnum = {
  id: 'id',
  agentId: 'agentId',
  phoneNumberId: 'phoneNumberId',
  providerCallId: 'providerCallId',
  providerName: 'providerName',
  direction: 'direction',
  fromNumber: 'fromNumber',
  toNumber: 'toNumber',
  status: 'status',
  disposition: 'disposition',
  outcomeType: 'outcomeType',
  detectedLanguage: 'detectedLanguage',
  sentiment: 'sentiment',
  durationSeconds: 'durationSeconds',
  recordingUrl: 'recordingUrl',
  recordingDeletedAt: 'recordingDeletedAt',
  transcriptJson: 'transcriptJson',
  transcriptText: 'transcriptText',
  summaryText: 'summaryText',
  extractedFields: 'extractedFields',
  callerName: 'callerName',
  callerEmail: 'callerEmail',
  callerPhone: 'callerPhone',
  costUnits: 'costUnits',
  processingStatus: 'processingStatus',
  processingError: 'processingError',
  startedAt: 'startedAt',
  endedAt: 'endedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VoiceCallEventScalarFieldEnum = {
  id: 'id',
  callId: 'callId',
  eventType: 'eventType',
  payload: 'payload',
  createdAt: 'createdAt'
};

exports.Prisma.VoiceBusinessHoursScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  dayOfWeek: 'dayOfWeek',
  openTime: 'openTime',
  closeTime: 'closeTime',
  isClosed: 'isClosed',
  isOverride: 'isOverride',
  overrideDate: 'overrideDate',
  overrideLabel: 'overrideLabel',
  aiMode: 'aiMode',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VoiceHandoffRuleScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  name: 'name',
  isActive: 'isActive',
  triggerType: 'triggerType',
  triggerValue: 'triggerValue',
  actionType: 'actionType',
  actionConfig: 'actionConfig',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VoiceKnowledgeBaseItemScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  itemType: 'itemType',
  title: 'title',
  content: 'content',
  tags: 'tags',
  isActive: 'isActive',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VoiceAppointmentRuleScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  name: 'name',
  isActive: 'isActive',
  bookingType: 'bookingType',
  calApiKey: 'calApiKey',
  calEventTypeId: 'calEventTypeId',
  bookingUrl: 'bookingUrl',
  bufferMinutes: 'bufferMinutes',
  minNoticeMinutes: 'minNoticeMinutes',
  maxDaysAhead: 'maxDaysAhead',
  slotDurationMin: 'slotDurationMin',
  conflictPolicy: 'conflictPolicy',
  confirmationMsg: 'confirmationMsg',
  requireFields: 'requireFields',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VoiceIntegrationScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  integrationType: 'integrationType',
  label: 'label',
  status: 'status',
  credentialsJson: 'credentialsJson',
  configJson: 'configJson',
  lastTestedAt: 'lastTestedAt',
  lastErrorMsg: 'lastErrorMsg',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VoiceNotificationConfigScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  channelType: 'channelType',
  label: 'label',
  isActive: 'isActive',
  triggerOn: 'triggerOn',
  config: 'config',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VoiceUsageRecordScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  callId: 'callId',
  billingMonth: 'billingMonth',
  durationSeconds: 'durationSeconds',
  billableMinutes: 'billableMinutes',
  costUnits: 'costUnits',
  overageUnits: 'overageUnits',
  overageCents: 'overageCents',
  createdAt: 'createdAt'
};

exports.Prisma.VoiceTestRunScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  agentId: 'agentId',
  toNumber: 'toNumber',
  providerCallId: 'providerCallId',
  status: 'status',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};


exports.Prisma.ModelName = {
  User: 'User',
  Session: 'Session',
  MagicLinkToken: 'MagicLinkToken',
  CardTemplate: 'CardTemplate',
  CardOrder: 'CardOrder',
  Subscription: 'Subscription',
  CardView: 'CardView',
  CardLead: 'CardLead',
  CardLink: 'CardLink',
  ScanEvent: 'ScanEvent',
  CardConnection: 'CardConnection',
  CardAlbumPhoto: 'CardAlbumPhoto',
  CardWebhook: 'CardWebhook',
  OrderStatusHistory: 'OrderStatusHistory',
  VoiceBillingPlan: 'VoiceBillingPlan',
  VoiceTenant: 'VoiceTenant',
  VoiceAgent: 'VoiceAgent',
  VoicePhoneNumber: 'VoicePhoneNumber',
  VoiceCall: 'VoiceCall',
  VoiceCallEvent: 'VoiceCallEvent',
  VoiceBusinessHours: 'VoiceBusinessHours',
  VoiceHandoffRule: 'VoiceHandoffRule',
  VoiceKnowledgeBaseItem: 'VoiceKnowledgeBaseItem',
  VoiceAppointmentRule: 'VoiceAppointmentRule',
  VoiceIntegration: 'VoiceIntegration',
  VoiceNotificationConfig: 'VoiceNotificationConfig',
  VoiceUsageRecord: 'VoiceUsageRecord',
  VoiceTestRun: 'VoiceTestRun'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
