// =============================================================================
// /c/[slug] — public Smart Card page.
//
// This route is reachable on three hostnames:
//   • opsolid.de/c/[slug]        — internal canonical (used by /api routes)
//   • card.opsolid.de/[slug]     — host-rewritten by middleware to /c/[slug]
//   • go.opsolid.de/[slug]       — Phase 3 will switch this to short-link gateway
//
// Renders the Smart Card layout with full feature set (services, gallery,
// FAQ, testimonials, video, brochure). Source query parameters
// (?src=…&campaign=…&event=…) are captured here so:
//   - the vCard download link inherits them (NOTE field gets the source label)
//   - lead form posts include them
//   - we can record a CardView with `source=` for analytics
// =============================================================================

import { existsSync } from "node:fs";
import { join } from "node:path";
import type * as React from "react";
import { notFound, permanentRedirect } from "next/navigation";
import { headers } from "next/headers";
import type { Metadata } from "next";
import { prisma } from "@/lib/prisma";
import { CardDataSchema } from "@/lib/validation";
import { SmartCard } from "@/components/cards/smart/SmartCard";
import { WalletButtons } from "@/components/cards/smart/WalletButtons";
import { readSourceFromSearchParams } from "@/components/cards/smart/SmartCardSource";
import { getSiteUrl } from "@/lib/stripe";
import { getTemplateEntry } from "@/components/cards/templates/v2/registry";
import { CustomSectionsBlock } from "@/components/cards/templates/v2/shared/CustomSectionsBlock";
import { OwnerModeProvider } from "@/context/OwnerMode";
import { QRFlipOverlay } from "@/components/cards/QRFlipOverlay";
import { ShareButton } from "@/components/cards/ShareButton";
import { OwnerToolbar } from "@/components/cards/OwnerToolbar";
import { StatusBanner } from "@/components/cards/StatusBanner";
import { LocaleSwitcher } from "@/components/cards/LocaleSwitcher";
import { SaveCardButton } from "@/components/cards/SaveCardButton";
import { constantTimeEquals } from "@/lib/constantTime";
import { contents } from "@/content";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

interface PageProps {
  params: Promise<{ slug: string }>;
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}

async function loadOrder(slug: string) {
  const order = await prisma.cardOrder.findUnique({
    where: { slug },
  });
  if (!order || order.status !== "PUBLISHED") return null;
  return order;
}

/**
 * Phase 8 — when a slug doesn't resolve directly, look it up in slug_history
 * (populated when the owner renames their card). Returns the current slug
 * so the caller can issue a 308 redirect.
 */
async function findRenamedSlug(oldSlug: string): Promise<string | null> {
  const order = await prisma.cardOrder.findFirst({
    where: {
      status: "PUBLISHED",
      slugHistory: { has: oldSlug },
    },
    select: { slug: true },
  });
  return order?.slug ?? null;
}

/**
 * Public-facing canonical URL — prefers the `card.opsolid.de` subdomain when
 * the page was accessed from there, otherwise falls back to opsolid.de/c/[slug].
 * Used in <link rel="canonical"> and Open Graph URLs to keep social previews
 * pointing at the prettier hostname.
 */
async function publicCardUrl(slug: string): Promise<string> {
  const h = await headers();
  const host = (h.get("host") || "").toLowerCase();
  if (host === "card.opsolid.de" || host === "go.opsolid.de") {
    return `https://card.opsolid.de/${slug}`;
  }
  const site = getSiteUrl().replace(/\/$/, "");
  return `${site}/c/${slug}`;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const order = await loadOrder(slug);
  // Phase 8.1 — private cards must not leak metadata to crawlers/scrapers.
  if (!order || order.visibility === 'private') return { title: "OpSolid Smart Card", robots: { index: false } };

  const card = CardDataSchema.safeParse(order.cardData);
  const name = card.success ? card.data.name : order.contactName;
  const title = card.success ? card.data.title : "";
  const company = card.success ? card.data.company : "";
  const bio = card.success ? card.data.bio : undefined;

  const url = await publicCardUrl(slug);
  const siteOrigin = getSiteUrl().replace(/\/$/, "");

  // Phase 7.5 — per-template thumbnail as the primary OG image. The
  // thumbnails are static PNGs generated by `npm run generate-thumbnails`
  // and committed under `public/images/templates/`. We probe the file
  // system once per metadata call to decide whether to advertise the
  // static thumbnail at all — if it isn't on disk (templateId without a
  // generated thumbnail, or a fresh checkout that hasn't run the script
  // yet), we omit it and let the dynamic OG do the work. This keeps
  // social-platform unfurls from following a 404 to the static asset.
  //
  // `existsSync` runs server-side at request time and is cheap (one
  // stat() per render). The file path is derived from `templateId`
  // which is validated by Prisma — no path-traversal surface.
  const thumbFilename = `card-${String(order.templateId).padStart(2, "0")}.png`;
  const thumbDiskPath = join(
    process.cwd(),
    "public",
    "images",
    "templates",
    thumbFilename,
  );
  const templateThumbExists = existsSync(thumbDiskPath);
  const templateThumbUrl = `${siteOrigin}/images/templates/${thumbFilename}`;

  // Build the OG image array. Order matters: most social platforms pick
  // the first image they can fetch successfully.
  //   1. Personalized wa.png 1080×1350 4:5 — tall hero with the card's
  //      actual photo + name, what users actually want to see in chats.
  //   2. Personalized og.png 1200×630 — wide card for Twitter/LinkedIn.
  //   3. Per-template static thumbnail — last-resort fallback if the
  //      dynamic routes are slow or rate-limited; not picked first
  //      because it's a generic template image, not the user's card.
  const altText = `${name}${company ? " · " + company : ""}`;
  // Cache-busting: every save updates `order.updatedAt` (Prisma @updatedAt).
  // Social scrapers (WhatsApp, Telegram, LinkedIn) hash the URL to key their
  // preview cache — appending the epoch timestamp ensures each save produces
  // a URL that scrapers treat as a new resource, bypassing stale previews.
  // The image route handlers ignore query parameters; Next.js revalidate=60
  // remains in effect and is keyed on the path only (no behaviour change).
  const v = order.updatedAt.getTime();
  const ogImages: NonNullable<NonNullable<Metadata["openGraph"]>["images"]> = [
    {
      url: `/c/${slug}/wa.png?v=${v}`,
      width: 1080,
      height: 1350,
      alt: altText,
    },
    {
      url: `/c/${slug}/og.png?v=${v}`,
      width: 1200,
      height: 630,
      alt: altText,
    },
  ];
  if (templateThumbExists) {
    ogImages.push({
      url: templateThumbUrl,
      width: 540,
      height: 960,
      alt: altText,
    });
  }

  const twitterImages: string[] = [`/c/${slug}/og.png?v=${v}`];
  if (templateThumbExists) twitterImages.push(templateThumbUrl);

  return {
    title: `${name}${title ? " — " + title : ""} · OpSolid Smart Card`,
    description: bio ?? company ?? "Digital business card — OpSolid Smart Card",
    alternates: { canonical: url },
    openGraph: {
      title: `${name}${company ? " · " + company : ""}`,
      description: bio,
      type: "profile",
      url,
      images: ogImages,
    },
    twitter: {
      card: "summary_large_image",
      images: twitterImages,
    },
    robots: { index: true, follow: true },
  };
}

export default async function CardPage({ params, searchParams }: PageProps) {
  const { slug } = await params;
  const sp = await searchParams;
  const order = await loadOrder(slug);
  if (!order) {
    // Phase 8 — owner may have renamed their card. Try slug_history before
    // giving up, then 308-redirect so old WhatsApp / QR links keep working.
    const renamed = await findRenamedSlug(slug);
    if (renamed) permanentRedirect(`/c/${renamed}`);
    notFound();
  }

  // Phase 8.1 — visibility enforcement on the page route.
  // "private" cards return 404 to all visitors. Owners can still reach their
  // card via the dashboard edit link (which uses a different route). This is
  // an MVP-safe check: no session reading, consistent with API route behaviour.
  // "unlisted" cards are accessible by direct link — no action needed here.
  if (order.visibility === 'private') {
    notFound();
  }

  const parsed = CardDataSchema.safeParse(order.cardData);
  if (!parsed.success) {
    // Phase 8 — log the parse failure so prod logs surface the bad field
    // instead of silently 404-ing. The slug is a public identifier; the
    // issue list is a small zod report. Safe to log.
    console.error("[card render] CardDataSchema parse failed", {
      slug,
      orderId: order.id,
      issues: parsed.error.issues.map((i) => ({
        path: i.path.join("."),
        message: i.message,
      })),
    });
    notFound();
  }

  const source = readSourceFromSearchParams(sp);

  // Fire-and-forget view tracking. We deliberately await on a Promise.race
  // so a slow DB write can't block the page render — the render proceeds
  // either way, and Prisma queues the insert.
  void prisma.cardView
    .create({
      data: {
        orderId: order.id,
        source: source.src ?? source.medium ?? null,
        ua: ((await headers()).get("user-agent") ?? "").slice(0, 200) || null,
        referer: (await headers()).get("referer")?.slice(0, 500) ?? null,
      },
    })
    .catch(() => {});

  const siteUrl = getSiteUrl();

  // Faz 6.7 B4 — visitor language priority: ?lang= > order.locale > "de" default.
  // Validate against the supported locale set so ?lang=foo gracefully falls
  // back instead of blowing up downstream consumers.
  const requestedLang = (sp.lang ?? "").toString().toLowerCase();
  const validLang = (["de", "en", "tr"] as const).includes(
    requestedLang as "de" | "en" | "tr",
  )
    ? (requestedLang as "de" | "en" | "tr")
    : null;
  const localeKey: "de" | "en" | "tr" =
    validLang ??
    (order.locale === "en" || order.locale === "tr" ? order.locale : "de");

  // v2 registry lookup. Falls back to SmartCard when the order's templateId
  // hasn't been ported yet — preserves existing live cards 1:1.
  const entry = getTemplateEntry(order.templateId);
  const Template = entry?.Component ?? SmartCard;

  // Phase 7.9 — image position + typography preset wiring (CSS variables on a
  // wrapper). Same logic as the form-side LivePreview so what the customer
  // configured renders identically here.
  const photoPos = parsed.data.photoPosition;
  const logoPos = parsed.data.logoPosition;
  const wrapperStyle: React.CSSProperties = {
    "--tpl-photo-x": `${photoPos?.x ?? 50}%`,
    "--tpl-photo-y": `${photoPos?.y ?? 50}%`,
    "--tpl-photo-scale": String(photoPos?.scale ?? 1),
    "--tpl-logo-x": `${logoPos?.x ?? 50}%`,
    "--tpl-logo-y": `${logoPos?.y ?? 50}%`,
    "--tpl-logo-scale": String(logoPos?.scale ?? 1),
  } as React.CSSProperties;
  // Phase 8 — typography preset is best-effort. A missing/renamed preset
  // file or font value used to crash the SSR render; we now log + ignore.
  if (parsed.data.typographyPreset && parsed.data.typographyPreset !== "default") {
    try {
      const { getTypographyPreset } = await import("@/lib/typographyPresets");
      const preset = getTypographyPreset(parsed.data.typographyPreset);
      if (preset?.displayFamily) {
        (wrapperStyle as Record<string, string>)["--tpl-font-display"] =
          preset.displayFamily;
      }
      if (preset?.bodyFamily) {
        (wrapperStyle as Record<string, string>)["--tpl-font-body"] =
          preset.bodyFamily;
      }
    } catch (e) {
      console.error("[card render] typography preset load failed", {
        slug,
        preset: parsed.data.typographyPreset,
        error: e instanceof Error ? e.message : String(e),
      });
    }
  }

  const isDarkTemplate = entry
    ? ["barber", "developer", "music-producer", "studio", "tech-startup"].includes(
        entry.key
      )
    : false;

  const publicUrl = await publicCardUrl(slug);
  const shareTitle = `${parsed.data.name}${parsed.data.company ? " · " + parsed.data.company : ""}`;
  const qrLabels = contents[localeKey].card.qr;

  // Phase 8 — owner toolbar. Visitors who arrive with `?owner=<editToken>` are
  // promoted to "owner view": a small floating bar with edit + share affordances
  // appears at the top of the page. The token is verified in constant time
  // against `order.editToken`; mismatched values silently fall through to the
  // public render path.
  const ownerTokenRaw = sp.owner;
  const ownerToken =
    typeof ownerTokenRaw === "string" ? ownerTokenRaw : ownerTokenRaw?.[0];
  const isOwner = Boolean(
    ownerToken &&
      order.editToken &&
      constantTimeEquals(ownerToken, order.editToken),
  );
  const ownerLabels = contents[localeKey].card.owner;
  const langSwitcherLabel = contents[localeKey].card.languageSwitcher;
  const editHref = `/${localeKey}/card/edit/${order.id}?t=${order.editToken ?? ""}`;

  return (
    <OwnerModeProvider isOwner={isOwner}>
      <main className="flex min-h-[100dvh] flex-col bg-bg-0 px-4 py-6 pb-24 sm:py-10">
        {isOwner && (
          <OwnerToolbar
            editHref={editHref}
            publicUrl={publicUrl}
            shareTitle={shareTitle}
            labels={{
              publicBannerLabel: ownerLabels.publicBannerLabel,
              editLabel: ownerLabels.editLabel,
              shareLabel: ownerLabels.shareLabel,
            }}
          />
        )}
        {parsed.data.statusMessage?.text?.trim() ? (
          <StatusBanner
            text={parsed.data.statusMessage.text}
            tone={parsed.data.statusMessage.tone}
            accentHex={order.brandAccentHex}
          />
        ) : null}
        <div
          className="mx-auto w-full max-w-[420px] flex-1"
          data-card-tpl
          style={wrapperStyle}
        >
          <Template
            slug={slug}
            cardData={parsed.data}
            photoPath={order.photoPath}
            logoPath={order.logoPath}
            brandPrimaryHex={order.brandPrimaryHex}
            brandAccentHex={order.brandAccentHex}
            source={source}
            siteUrl={siteUrl}
            locale={localeKey}
            walletSlot={<WalletButtons slug={slug} />}
          />
          <CustomSectionsBlock
            sections={parsed.data.customSections}
            accentHex={order.brandAccentHex ?? undefined}
            tone={isDarkTemplate ? "dark" : "light"}
          />
          {/* Phase 8.3 — save + locale row below card content */}
          <div className="mt-6 flex flex-wrap items-center justify-center gap-3">
            {/* Only show save button to non-owners — owners manage via dashboard */}
            {!isOwner && (
              <SaveCardButton slug={slug} locale={localeKey} />
            )}
            <LocaleSwitcher current={localeKey} ariaLabel={langSwitcherLabel} />
          </div>
        </div>
        <QRFlipOverlay
          slug={slug}
          publicUrl={publicUrl}
          shareTitle={shareTitle}
          accentHex={order.brandAccentHex ?? undefined}
          labels={qrLabels}
        />
        {/* Phase 5 — share drawer trigger (bottom-left, QR occupies bottom-right) */}
        <ShareButton
          slug={slug}
          accentHex={order.brandAccentHex ?? undefined}
          locale={localeKey}
        />
      </main>
    </OwnerModeProvider>
  );
}
