// =============================================================================
// /c/[slug] — public Smart Card page.
//
// This route is reachable on three hostnames:
//   • opsolid.de/c/[slug]        — internal canonical (used by /api routes)
//   • card.opsolid.de/[slug]     — host-rewritten by middleware to /c/[slug]
//   • go.opsolid.de/[slug]       — Phase 3 will switch this to short-link gateway
//
// Renders the Smart Card layout with full feature set (services, gallery,
// FAQ, testimonials, video, brochure). Source query parameters
// (?src=…&campaign=…&event=…) are captured here so:
//   - the vCard download link inherits them (NOTE field gets the source label)
//   - lead form posts include them
//   - we can record a CardView with `source=` for analytics
// =============================================================================

import { existsSync } from "node:fs";
import { join } from "node:path";
import { notFound } from "next/navigation";
import { headers } from "next/headers";
import type { Metadata } from "next";
import { prisma } from "@/lib/prisma";
import { CardDataSchema } from "@/lib/validation";
import { SmartCard } from "@/components/cards/smart/SmartCard";
import { WalletButtons } from "@/components/cards/smart/WalletButtons";
import { readSourceFromSearchParams } from "@/components/cards/smart/SmartCardSource";
import { getSiteUrl } from "@/lib/stripe";
import { getTemplateEntry } from "@/components/cards/templates/v2/registry";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

interface PageProps {
  params: Promise<{ slug: string }>;
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}

async function loadOrder(slug: string) {
  const order = await prisma.cardOrder.findUnique({
    where: { slug },
  });
  if (!order || order.status !== "PUBLISHED") return null;
  return order;
}

/**
 * Public-facing canonical URL — prefers the `card.opsolid.de` subdomain when
 * the page was accessed from there, otherwise falls back to opsolid.de/c/[slug].
 * Used in <link rel="canonical"> and Open Graph URLs to keep social previews
 * pointing at the prettier hostname.
 */
async function publicCardUrl(slug: string): Promise<string> {
  const h = await headers();
  const host = (h.get("host") || "").toLowerCase();
  if (host === "card.opsolid.de" || host === "go.opsolid.de") {
    return `https://card.opsolid.de/${slug}`;
  }
  const site = getSiteUrl().replace(/\/$/, "");
  return `${site}/c/${slug}`;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const order = await loadOrder(slug);
  if (!order) return { title: "OpSolid Smart Card", robots: { index: false } };

  const card = CardDataSchema.safeParse(order.cardData);
  const name = card.success ? card.data.name : order.contactName;
  const title = card.success ? card.data.title : "";
  const company = card.success ? card.data.company : "";
  const bio = card.success ? card.data.bio : undefined;

  const url = await publicCardUrl(slug);
  const siteOrigin = getSiteUrl().replace(/\/$/, "");

  // Phase 7.5 — per-template thumbnail as the primary OG image. The
  // thumbnails are static PNGs generated by `npm run generate-thumbnails`
  // and committed under `public/images/templates/`. We probe the file
  // system once per metadata call to decide whether to advertise the
  // static thumbnail at all — if it isn't on disk (templateId without a
  // generated thumbnail, or a fresh checkout that hasn't run the script
  // yet), we omit it and let the dynamic OG do the work. This keeps
  // social-platform unfurls from following a 404 to the static asset.
  //
  // `existsSync` runs server-side at request time and is cheap (one
  // stat() per render). The file path is derived from `templateId`
  // which is validated by Prisma — no path-traversal surface.
  const thumbFilename = `card-${String(order.templateId).padStart(2, "0")}.png`;
  const thumbDiskPath = join(
    process.cwd(),
    "public",
    "images",
    "templates",
    thumbFilename,
  );
  const templateThumbExists = existsSync(thumbDiskPath);
  const templateThumbUrl = `${siteOrigin}/images/templates/${thumbFilename}`;

  // Build the OG image array. Order matters: most social platforms
  // (Facebook, LinkedIn, X) pick the first image they can fetch
  // successfully.
  //   1. Per-template static thumbnail (Phase 7.5) — fast, branded,
  //      shipped as a PNG so unfurls never hit the dynamic OG route.
  //      Only included when the file actually exists on disk.
  //   2. Dynamic OG 1200×630 — legacy / per-card override path.
  //   3. WhatsApp 600×600 1:1 — chat-thumbnail aspect ratio.
  const altText = `${name}${company ? " · " + company : ""}`;
  const ogImages: NonNullable<NonNullable<Metadata["openGraph"]>["images"]> = [];
  if (templateThumbExists) {
    ogImages.push({
      url: templateThumbUrl,
      width: 540,
      height: 960,
      alt: altText,
    });
  }
  ogImages.push(
    {
      url: `/c/${slug}.png`,
      width: 1200,
      height: 630,
      alt: altText,
    },
    {
      url: `/c/${slug}/wa.png`,
      width: 600,
      height: 600,
      alt: altText,
    },
  );

  const twitterImages: string[] = [];
  if (templateThumbExists) twitterImages.push(templateThumbUrl);
  twitterImages.push(`/c/${slug}.png`);

  return {
    title: `${name}${title ? " — " + title : ""} · OpSolid Smart Card`,
    description: bio ?? company ?? "Digital business card — OpSolid Smart Card",
    alternates: { canonical: url },
    openGraph: {
      title: `${name}${company ? " · " + company : ""}`,
      description: bio,
      type: "profile",
      url,
      images: ogImages,
    },
    twitter: {
      card: "summary_large_image",
      images: twitterImages,
    },
    robots: { index: true, follow: true },
  };
}

export default async function CardPage({ params, searchParams }: PageProps) {
  const { slug } = await params;
  const sp = await searchParams;
  const order = await loadOrder(slug);
  if (!order) notFound();

  const parsed = CardDataSchema.safeParse(order.cardData);
  if (!parsed.success) notFound();

  const source = readSourceFromSearchParams(sp);

  // Fire-and-forget view tracking. We deliberately await on a Promise.race
  // so a slow DB write can't block the page render — the render proceeds
  // either way, and Prisma queues the insert.
  void prisma.cardView
    .create({
      data: {
        orderId: order.id,
        source: source.src ?? source.medium ?? null,
        ua: ((await headers()).get("user-agent") ?? "").slice(0, 200) || null,
        referer: (await headers()).get("referer")?.slice(0, 500) ?? null,
      },
    })
    .catch(() => {});

  const siteUrl = getSiteUrl();
  const localeKey: "de" | "en" | "tr" =
    order.locale === "en" || order.locale === "tr" ? order.locale : "de";

  // v2 registry lookup. Falls back to SmartCard when the order's templateId
  // hasn't been ported yet — preserves existing live cards 1:1.
  const entry = getTemplateEntry(order.templateId);
  const Template = entry?.Component ?? SmartCard;

  return (
    <main className="min-h-screen bg-bg-0 px-4 py-8 pb-24 sm:py-12">
      <div className="mx-auto w-full max-w-[460px]">
        <Template
          slug={slug}
          cardData={parsed.data}
          photoPath={order.photoPath}
          logoPath={order.logoPath}
          brandPrimaryHex={order.brandPrimaryHex}
          brandAccentHex={order.brandAccentHex}
          source={source}
          siteUrl={siteUrl}
          locale={localeKey}
          walletSlot={<WalletButtons slug={slug} />}
        />
      </div>
    </main>
  );
}
