// =============================================================================
// AUTO-GENERATED by scripts/gen-labels-registry.ts — DO NOT EDIT BY HAND.
// Re-run the generator after adding a template or changing a registry key.
//
// Maps each template's registry `key` to its exported `COPY` table so the
// order form / live editor can list a template's editable section-label keys
// and their localized defaults (placeholder text). Reading the live COPY keeps
// the editor in lockstep with what each template actually renders.
//
// Server-safe (no "use client"): mirrors registry.ts, which already reads plain
// objects exported from the client template modules.
// =============================================================================

import * as M_Accounting from "./Accounting";
import * as M_AccountingNoir from "./AccountingNoir";
import * as M_AccountingPure from "./AccountingPure";
import * as M_Architect from "./Architect";
import * as M_ArchitectNoir from "./ArchitectNoir";
import * as M_ArchitectPure from "./ArchitectPure";
import * as M_ArchitectStone from "./ArchitectStone";
import * as M_ArchitectVivid from "./ArchitectVivid";
import * as M_Atelier from "./Atelier";
import * as M_Athlete from "./Athlete";
import * as M_AutoDealer from "./AutoDealer";
import * as M_AutoDealerPure from "./AutoDealerPure";
import * as M_AutoDealerVivid from "./AutoDealerVivid";
import * as M_Barber from "./Barber";
import * as M_BarberNoir from "./BarberNoir";
import * as M_BarberPure from "./BarberPure";
import * as M_BarberStone from "./BarberStone";
import * as M_BarberVivid from "./BarberVivid";
import * as M_BeautySalon from "./BeautySalon";
import * as M_BeautySalonNoir from "./BeautySalonNoir";
import * as M_BeautySalonPure from "./BeautySalonPure";
import * as M_BlankCanvas from "./BlankCanvas";
import * as M_Clinic from "./Clinic";
import * as M_ClinicNoir from "./ClinicNoir";
import * as M_ClinicPure from "./ClinicPure";
import * as M_ClinicStone from "./ClinicStone";
import * as M_ClinicVivid from "./ClinicVivid";
import * as M_ContentCreator from "./ContentCreator";
import * as M_ContentCreatorNoir from "./ContentCreatorNoir";
import * as M_ContentCreatorPure from "./ContentCreatorPure";
import * as M_Dentist from "./Dentist";
import * as M_DentistPure from "./DentistPure";
import * as M_DentistVivid from "./DentistVivid";
import * as M_Developer from "./Developer";
import * as M_DJNoir from "./DJNoir";
import * as M_DJPure from "./DJPure";
import * as M_DJStone from "./DJStone";
import * as M_DJVivid from "./DJVivid";
import * as M_Ecommerce from "./Ecommerce";
import * as M_EcommerceNoir from "./EcommerceNoir";
import * as M_EcommercePure from "./EcommercePure";
import * as M_EcommerceVivid from "./EcommerceVivid";
import * as M_Editorial from "./Editorial";
import * as M_EventPlanner from "./EventPlanner";
import * as M_EventPlannerNoir from "./EventPlannerNoir";
import * as M_EventPlannerPure from "./EventPlannerPure";
import * as M_FitnessNoir from "./FitnessNoir";
import * as M_FitnessPure from "./FitnessPure";
import * as M_FitnessStone from "./FitnessStone";
import * as M_FitnessVivid from "./FitnessVivid";
import * as M_Hotel from "./Hotel";
import * as M_InteriorDesign from "./InteriorDesign";
import * as M_InteriorDesignNoir from "./InteriorDesignNoir";
import * as M_InteriorDesignVivid from "./InteriorDesignVivid";
import * as M_KitchenAtelier from "./KitchenAtelier";
import * as M_LayoutEditorial from "./LayoutEditorial";
import * as M_LayoutNoirLuxury from "./LayoutNoirLuxury";
import * as M_LayoutPureSwiss from "./LayoutPureSwiss";
import * as M_LayoutSplitScreen from "./LayoutSplitScreen";
import * as M_LayoutVividBold from "./LayoutVividBold";
import * as M_LegalCounsel from "./LegalCounsel";
import * as M_LegalCounselNoir from "./LegalCounselNoir";
import * as M_LegalCounselPure from "./LegalCounselPure";
import * as M_LegalCounselStone from "./LegalCounselStone";
import * as M_LegalCounselVivid from "./LegalCounselVivid";
import * as M_Maker from "./Maker";
import * as M_MusicProducer from "./MusicProducer";
import * as M_PersonalTrainer from "./PersonalTrainer";
import * as M_Photographer from "./Photographer";
import * as M_PhotographerNoir from "./PhotographerNoir";
import * as M_PhotographerPure from "./PhotographerPure";
import * as M_PhotographerStone from "./PhotographerStone";
import * as M_PhotographerVivid from "./PhotographerVivid";
import * as M_Psychologist from "./Psychologist";
import * as M_PsychologistPure from "./PsychologistPure";
import * as M_PsychologistVivid from "./PsychologistVivid";
import * as M_RealEstate from "./RealEstate";
import * as M_RealEstateNoir from "./RealEstateNoir";
import * as M_RealEstatePure from "./RealEstatePure";
import * as M_RealEstateStone from "./RealEstateStone";
import * as M_RealEstateVivid from "./RealEstateVivid";
import * as M_Restaurant from "./Restaurant";
import * as M_RestaurantNoir from "./RestaurantNoir";
import * as M_RestaurantPure from "./RestaurantPure";
import * as M_RestaurantStone from "./RestaurantStone";
import * as M_RestaurantVivid from "./RestaurantVivid";
import * as M_SoftwareDev from "./SoftwareDev";
import * as M_SoftwareDevPure from "./SoftwareDevPure";
import * as M_SoftwareDevVivid from "./SoftwareDevVivid";
import * as M_Studio from "./Studio";
import * as M_TechStartup from "./TechStartup";
import * as M_Universal from "./Universal";
import * as M_WeddingPlanner from "./WeddingPlanner";
import * as M_WellnessTeacher from "./WellnessTeacher";
import * as M_WellnessTeacherPure from "./WellnessTeacherPure";
import * as M_WellnessTeacherVivid from "./WellnessTeacherVivid";
import * as M_YogaStudio from "./YogaStudio";

/** Editable section-label keys -> default text, for one locale. */
export type LabelDefaults = Record<string, string>;
/** Locale -> LabelDefaults. The template COPY tables satisfy this at runtime;
 *  the cast bridges the interface (no index signature) -> Record gap. */
export type LabelCopyTable = Partial<
  Record<"de" | "en" | "tr" | "es" | "it" | "fr" | "ar", LabelDefaults>
>;

const tbl = (copy: unknown): LabelCopyTable => copy as LabelCopyTable;


/** template registry key -> its localized label copy table. */
export const labelsRegistry: Record<string, LabelCopyTable> = {
  "accounting": tbl(M_Accounting.COPY),
  "accounting-noir": tbl(M_AccountingNoir.COPY),
  "accounting-pure": tbl(M_AccountingPure.COPY),
  "architect": tbl(M_Architect.COPY),
  "architect-noir": tbl(M_ArchitectNoir.COPY),
  "architect-pure": tbl(M_ArchitectPure.COPY),
  "architect-stone": tbl(M_ArchitectStone.COPY),
  "architect-vivid": tbl(M_ArchitectVivid.COPY),
  "atelier": tbl(M_Atelier.COPY),
  "athlete": tbl(M_Athlete.COPY),
  "auto-dealer": tbl(M_AutoDealer.COPY),
  "auto-dealer-pure": tbl(M_AutoDealerPure.COPY),
  "auto-dealer-vivid": tbl(M_AutoDealerVivid.COPY),
  "barber": tbl(M_Barber.COPY),
  "barber-noir": tbl(M_BarberNoir.COPY),
  "barber-pure": tbl(M_BarberPure.COPY),
  "barber-stone": tbl(M_BarberStone.COPY),
  "barber-vivid": tbl(M_BarberVivid.COPY),
  "beauty-salon": tbl(M_BeautySalon.COPY),
  "beauty-salon-noir": tbl(M_BeautySalonNoir.COPY),
  "beauty-salon-pure": tbl(M_BeautySalonPure.COPY),
  "blank-canvas": tbl(M_BlankCanvas.COPY),
  "clinic": tbl(M_Clinic.COPY),
  "clinic-noir": tbl(M_ClinicNoir.COPY),
  "clinic-pure": tbl(M_ClinicPure.COPY),
  "clinic-stone": tbl(M_ClinicStone.COPY),
  "clinic-vivid": tbl(M_ClinicVivid.COPY),
  "content-creator": tbl(M_ContentCreator.COPY),
  "content-creator-noir": tbl(M_ContentCreatorNoir.COPY),
  "content-creator-pure": tbl(M_ContentCreatorPure.COPY),
  "dentist": tbl(M_Dentist.COPY),
  "dentist-pure": tbl(M_DentistPure.COPY),
  "dentist-vivid": tbl(M_DentistVivid.COPY),
  "developer": tbl(M_Developer.COPY),
  "dj-noir": tbl(M_DJNoir.COPY),
  "dj-pure": tbl(M_DJPure.COPY),
  "dj-stone": tbl(M_DJStone.COPY),
  "dj-vivid": tbl(M_DJVivid.COPY),
  "ecommerce": tbl(M_Ecommerce.COPY),
  "ecommerce-noir": tbl(M_EcommerceNoir.COPY),
  "ecommerce-pure": tbl(M_EcommercePure.COPY),
  "ecommerce-vivid": tbl(M_EcommerceVivid.COPY),
  "editorial": tbl(M_Editorial.COPY),
  "event-planner": tbl(M_EventPlanner.COPY),
  "event-planner-noir": tbl(M_EventPlannerNoir.COPY),
  "event-planner-pure": tbl(M_EventPlannerPure.COPY),
  "fitness-noir": tbl(M_FitnessNoir.COPY),
  "fitness-pure": tbl(M_FitnessPure.COPY),
  "fitness-stone": tbl(M_FitnessStone.COPY),
  "fitness-vivid": tbl(M_FitnessVivid.COPY),
  "hotel": tbl(M_Hotel.COPY),
  "interior-design": tbl(M_InteriorDesign.COPY),
  "interior-design-noir": tbl(M_InteriorDesignNoir.COPY),
  "interior-design-vivid": tbl(M_InteriorDesignVivid.COPY),
  "kitchen-atelier": tbl(M_KitchenAtelier.COPY),
  "layout-editorial": tbl(M_LayoutEditorial.COPY),
  "layout-noir-luxury": tbl(M_LayoutNoirLuxury.COPY),
  "layout-pure-swiss": tbl(M_LayoutPureSwiss.COPY),
  "layout-split-screen": tbl(M_LayoutSplitScreen.COPY),
  "layout-vivid-bold": tbl(M_LayoutVividBold.COPY),
  "legal-counsel": tbl(M_LegalCounsel.COPY),
  "legal-counsel-noir": tbl(M_LegalCounselNoir.COPY),
  "legal-counsel-pure": tbl(M_LegalCounselPure.COPY),
  "legal-counsel-stone": tbl(M_LegalCounselStone.COPY),
  "legal-counsel-vivid": tbl(M_LegalCounselVivid.COPY),
  "maker": tbl(M_Maker.COPY),
  "music-producer": tbl(M_MusicProducer.COPY),
  "personal-trainer": tbl(M_PersonalTrainer.COPY),
  "photographer": tbl(M_Photographer.COPY),
  "photographer-noir": tbl(M_PhotographerNoir.COPY),
  "photographer-pure": tbl(M_PhotographerPure.COPY),
  "photographer-stone": tbl(M_PhotographerStone.COPY),
  "photographer-vivid": tbl(M_PhotographerVivid.COPY),
  "psychologist": tbl(M_Psychologist.COPY),
  "psychologist-pure": tbl(M_PsychologistPure.COPY),
  "psychologist-vivid": tbl(M_PsychologistVivid.COPY),
  "real-estate": tbl(M_RealEstate.COPY),
  "real-estate-noir": tbl(M_RealEstateNoir.COPY),
  "real-estate-pure": tbl(M_RealEstatePure.COPY),
  "real-estate-stone": tbl(M_RealEstateStone.COPY),
  "real-estate-vivid": tbl(M_RealEstateVivid.COPY),
  "restaurant": tbl(M_Restaurant.COPY),
  "restaurant-noir": tbl(M_RestaurantNoir.COPY),
  "restaurant-pure": tbl(M_RestaurantPure.COPY),
  "restaurant-stone": tbl(M_RestaurantStone.COPY),
  "restaurant-vivid": tbl(M_RestaurantVivid.COPY),
  "software-dev": tbl(M_SoftwareDev.COPY),
  "software-dev-pure": tbl(M_SoftwareDevPure.COPY),
  "software-dev-vivid": tbl(M_SoftwareDevVivid.COPY),
  "studio": tbl(M_Studio.COPY),
  "tech-startup": tbl(M_TechStartup.COPY),
  "universal": tbl(M_Universal.COPY),
  "wedding-planner": tbl(M_WeddingPlanner.COPY),
  "wellness-teacher": tbl(M_WellnessTeacher.COPY),
  "wellness-teacher-pure": tbl(M_WellnessTeacherPure.COPY),
  "wellness-teacher-vivid": tbl(M_WellnessTeacherVivid.COPY),
  "yoga-studio": tbl(M_YogaStudio.COPY),
};

/**
 * The editable label keys + localized default text for a template key in the
 * given locale. Returns [] for unknown templates (the editor then renders no
 * label group). Falls back to the German defaults when the locale is missing.
 */
export function getEditableLabels(
  templateKey: string | undefined | null,
  locale: string,
): Array<{ key: string; default: string }> {
  if (!templateKey) return [];
  const table = labelsRegistry[templateKey];
  if (!table) return [];
  const defaults = (table as Record<string, LabelDefaults | undefined>)[locale] ?? table.de;
  if (!defaults) return [];
  return Object.entries(defaults).map(([key, value]) => ({ key, default: value }));
}
