import type { Metadata, Viewport } from "next";
import { headers } from "next/headers";
import {
  Inter,
  Instrument_Serif,
  JetBrains_Mono,
  Plus_Jakarta_Sans,
  Fira_Code,
} from "next/font/google";
import { ConditionalAnalytics } from "@/components/shared/ConditionalAnalytics";
import { SITE_CONFIG } from "@/lib/constants";
import { isLocale, DEFAULT_LOCALE, directionForLocale } from "@/lib/i18n";
import { ConsentBanner } from "@/components/shared/ConsentBanner";
import "./globals.css";

const inter = Inter({
  subsets: ["latin", "latin-ext"],
  display: "swap",
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
});

// V2 redesign font stack — Plus Jakarta Sans serves both display and body
// roles (weight contrast carries hierarchy), Fira Code as mono.
// Loaded site-wide so v2 pages don't pay a font-network round-trip on
// first paint when toggling the ?preview=v2 gate.
const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin", "latin-ext"],
  display: "swap",
  variable: "--font-v2-body",
  weight: ["400", "500", "600", "700", "800"],
});

const firaCode = Fira_Code({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-v2-mono",
  weight: ["400", "500"],
});

// Geist isn't a Google Font at this time; Vercel ships it as a static file
// in the `geist` npm package. We keep it optional — if the package is
// missing, the CSS stack falls back to Inter for display.
let geistVariable = "";
try {
  // Dynamic require so missing dep in CI doesn't break the build.
  // eslint-disable-next-line @typescript-eslint/no-var-requires, @typescript-eslint/no-require-imports
  const { GeistSans } = require("geist/font/sans");
  geistVariable = GeistSans.variable;
} catch {
  geistVariable = "";
}

const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-instrument-serif",
  weight: ["400"],
  style: ["normal", "italic"],
});

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jetbrains-mono",
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_CONFIG.url),
  title: {
    default: `${SITE_CONFIG.name} — ${SITE_CONFIG.tagline}`,
    template: `%s | ${SITE_CONFIG.name}`,
  },
  description: SITE_CONFIG.description,
  keywords: [
    "KI Beratung Mittelstand",
    "KI Beratung für Unternehmen",
    "Automatisierung Beratung",
    "Prozessautomatisierung Unternehmen",
    "Geschäftsprozesse automatisieren",
    "Microsoft 365 Automatisierung",
    "Power Automate Beratung",
    "KI Schulung Unternehmen",
    "Digitalisierung Mittelstand",
    "Workflow Automatisierung",
    "KI Prozessoptimierung",
    "AI consulting",
    "AI automation",
    "SME automation",
    "Germany",
    "Mittelstand",
    "B2B",
  ],
  authors: [{ name: SITE_CONFIG.name }],
  creator: SITE_CONFIG.name,
  openGraph: {
    type: "website",
    url: SITE_CONFIG.url,
    siteName: SITE_CONFIG.name,
    title: `${SITE_CONFIG.name} — ${SITE_CONFIG.tagline}`,
    description: SITE_CONFIG.description,
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE_CONFIG.name} — ${SITE_CONFIG.tagline}`,
    description: SITE_CONFIG.description,
  },
  robots: { index: true, follow: true },
  // Favicon set generated by scripts/generate-favicons.ts from the in-site
  // brand mark. Re-run that script if the mark changes.
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/icons/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/icons/favicon-16.png", sizes: "16x16", type: "image/png" },
    ],
    apple: [
      { url: "/icons/apple-touch-icon-180.png", sizes: "180x180", type: "image/png" },
    ],
    other: [
      { rel: "icon", url: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
      { rel: "mask-icon", url: "/icon.svg", color: "#C27940" },
    ],
  },
  manifest: "/site.webmanifest",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: [
    // M9 v2 promotion: Concrete Studio teal replaces legacy copper as the
    // primary accent across both light and dark UA chrome.
    { media: "(prefers-color-scheme: light)", color: "#0F766E" },
    { media: "(prefers-color-scheme: dark)", color: "#14B8A6" },
  ],
};

// Applied inline in <head> before hydration so the first paint already has
// the correct palette — avoids flash-of-wrong-theme. Mirrors
// src/context/ThemeContext.tsx (DEFAULT_THEME = "light", key = "opsolid-theme").
const NO_FLASH_THEME_SCRIPT = `(function(){try{var t=localStorage.getItem('opsolid-theme');if(t==='hybrid'){t='light';localStorage.setItem('opsolid-theme','light');}if(t!=='light'&&t!=='dark'){t='light';}document.documentElement.setAttribute('data-theme',t);}catch(e){document.documentElement.setAttribute('data-theme','light');}})();`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerStore = headers();
  const localeHeader = headerStore.get("x-locale");
  const lang = isLocale(localeHeader) ? localeHeader : DEFAULT_LOCALE;
  const dir = directionForLocale(lang);

  const fontClasses = [
    inter.variable,
    instrumentSerif.variable,
    jetBrainsMono.variable,
    geistVariable,
    plusJakartaSans.variable,
    firaCode.variable,
  ]
    .filter(Boolean)
    .join(" ");

  // M9 promotion (2026-05-19): v2 is now the default. The legacy gated
  // logic is kept commented for emergency rollback — flip back by
  // restoring the requestPath check and removing the constant.
  //   const requestPath = headerStore.get("x-pathname") ?? "";
  //   const previewV2 =
  //     requestPath.includes("preview=v2") ||
  //     requestPath.includes("preview%3Dv2");
  const previewV2 = true;

  return (
    <html
      lang={lang}
      dir={dir}
      className={fontClasses}
      data-preview={previewV2 ? "v2" : undefined}
      suppressHydrationWarning
    >
      <head>
        <script
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={{ __html: NO_FLASH_THEME_SCRIPT }}
        />
      </head>
      <body className="grain font-sans antialiased bg-bg-1 text-ink-200 min-h-[100svh] flex flex-col">
        {children}
        {/* C5 — ConsentBanner sets the localStorage flag; ConditionalAnalytics
            (a client component) watches it and only mounts <Analytics /> after
            the user accepts. We can't pass `beforeSend` from this server layout
            because RSC cannot serialize functions across the boundary. */}
        <ConsentBanner />
        <ConditionalAnalytics />
      </body>
    </html>
  );
}
