// =============================================================================
// OpSolid — Digital Business Card (DBC) Templates
//
// Source of truth for the template catalog. Numbered 1..N so customers can
// reference a design by its number ("Ich möchte Design #03"). The matching
// React component lives under src/components/cards/templates/<componentKey>.tsx
// and the thumbnail at /images/templates/card-<id>.png.
//
// Three billing modes per template:
//   - monthly (recurring)     — lowest-friction entry
//   - yearly  (recurring)     — ~35% discount vs monthly, the "sweet spot"
//   - one-time (lifetime)     — pricey anchor, rare in market
//
// Stripe Price IDs are populated by scripts/setup-stripe.ts. Re-run it with
// the LIVE secret key to get a parallel set for production.
// =============================================================================

export interface CardTemplateDef {
  id: number;
  slug: string;
  name: string;
  sectorHint:
    | "general"
    | "realEstate"
    | "salon"
    | "restaurant"
    | "creator"
    | "freelancer"
    | "lawyer"
    | "clinic"
    | "fitness"
    | "music"
    | "architecture"
    | "retail"
    | "hospitality"
    | "events"
    | "construction"
    | "tourism"
    | "corporate"
    | "tech"
    | "consultant"
    | "dentist"
    | "psychologist"
    | "beauty"
    | "accounting"
    | "software"
    | "content-creator"
    | "wellness"
    | "eventPlanner"
    | "auto"
    | "interior";
  componentKey:
    | "Template01"
    | "Template02"
    | "Template03"
    | "Template04"
    | "Template05"
    | "SmartCard";
  /**
   * Optional default theme preset for this template (Phase 6). The preview
   * thumbnail and the order form's "Style preset" select use this to seed
   * the customer's choice. CSS-only via `data-theme` on the SmartCard root —
   * no DOM swap. See src/lib/cardThemes.ts for available presets.
   */
  themeKey?: "aurora" | "editorial" | "cinema";
  previewPath: string;
  /** One-time "lifetime" purchase — no renewal. */
  oneTimeCents: number;
  /** Monthly subscription (EUR). Null = not offered for this template. */
  monthlyCents: number | null;
  /** Yearly subscription (EUR). Null = not offered. */
  yearlyCents: number | null;
  stripeOneTimePriceId?: string;
  stripeMonthlyPriceId?: string;
  stripeYearlyPriceId?: string;
  isActive: boolean;
  sortOrder: number;
  /**
   * Phase 7 marker. `true` for ids 13..20 — sector-tailored SmartCard presets
   * that don't yet have a hand-built v2 component. The Phase 7.2 carousel
   * filters these out so customers only see the curated 12-template line-up.
   * Legacy entries continue to render via SmartCard fallback for any
   * pre-existing CardOrder rows whose templateId points here.
   */
  legacy?: boolean;
}

export const cardTemplates: readonly CardTemplateDef[] = [
  // Pricing rationale (2026-04-23 rev2):
  //
  // Market floor references (researched 2026-04-23):
  //   TR: vTAG ₺79/ay Standard (~€2), vTAG Pro+ ₺129/ay (~€3.4), Digi Card
  //       Starter ₺299/ay (~€7.7). Physical NFC ₺500-600 one-time.
  //   Global: Blinq Premium $5.89/mo, Lemontaps €6/mo, Popl ~€60/yr teams.
  //
  // We match Blinq / Lemontaps on monthly (global market floor) and sit
  // ~40% below them on yearly — since our annual price anchors long-term.
  // One-time is deliberately priced ~1.5× yearly so subscription is the
  // obvious default.
  {
    id: 1,
    slug: "real-estate",
    // Phase 7.1 alignment — id=1 is the Real Estate (kart_01) v2 component.
    // Pricing/Stripe IDs unchanged; only the human-facing name + sector hint
    // are updated to match the v2 registry. The carousel and order form both
    // resolve visuals via templateRegistry[1], so the catalog entry only
    // governs billing + filter-pill metadata.
    name: "Real Estate",
    sectorHint: "realEstate",
    componentKey: "SmartCard",
    themeKey: "editorial",
    previewPath: "/images/templates/card-01.png",
    monthlyCents: 500, // €5 / month  (~₺190)
    yearlyCents: 3900, // €39 / year (~₺1.480) — 35% off monthly
    oneTimeCents: 7900, // €79 lifetime (~₺3.000)
    stripeOneTimePriceId: "price_1TPLkX25H593hnObbB3cDjRZ",
    stripeMonthlyPriceId: "price_1TPLkX25H593hnObFsuYfkwG",
    stripeYearlyPriceId: "price_1TPLkX25H593hnObhWn3obfm",
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 2,
    slug: "warm-serif",
    name: "Warm Serif",
    sectorHint: "creator",
    componentKey: "SmartCard",
    themeKey: "editorial",
    previewPath: "/images/templates/card-02.png",
    monthlyCents: 600, // €6 / month
    yearlyCents: 4900, // €49 / year
    oneTimeCents: 9900, // €99 lifetime
    stripeOneTimePriceId: "price_1TPLkY25H593hnObMOVYfp1B",
    stripeMonthlyPriceId: "price_1TPLkY25H593hnObd5Q7nkuA",
    stripeYearlyPriceId: "price_1TPLkY25H593hnObrtlEaUmW",
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 3,
    slug: "estate-brass",
    name: "Estate Brass",
    sectorHint: "realEstate",
    componentKey: "SmartCard",
    themeKey: "cinema",
    previewPath: "/images/templates/card-03.png",
    monthlyCents: 700, // €7 / month   (premium — real-estate buyer)
    yearlyCents: 5900, // €59 / year
    oneTimeCents: 12900, // €129 lifetime
    stripeOneTimePriceId: "price_1TPLkZ25H593hnObjnIT7vxk",
    stripeMonthlyPriceId: "price_1TPLkZ25H593hnObZUdrkDxI",
    stripeYearlyPriceId: "price_1TPLkZ25H593hnOb6qOoofB1",
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 4,
    slug: "atelier-clean",
    name: "Atelier Clean",
    sectorHint: "salon",
    componentKey: "SmartCard",
    themeKey: "aurora",
    previewPath: "/images/templates/card-04.png",
    monthlyCents: 600,
    yearlyCents: 4900,
    oneTimeCents: 9900,
    stripeOneTimePriceId: "price_1TPLka25H593hnObJmK5wAeF",
    stripeMonthlyPriceId: "price_1TPLka25H593hnObfAyNuZ0d",
    stripeYearlyPriceId: "price_1TPLka25H593hnObXq3wHwq0",
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 5,
    slug: "restaurant-noir",
    name: "Restaurant Noir",
    sectorHint: "restaurant",
    componentKey: "SmartCard",
    themeKey: "cinema",
    previewPath: "/images/templates/card-05.png",
    monthlyCents: 600,
    yearlyCents: 4900,
    oneTimeCents: 9900,
    stripeOneTimePriceId: "price_1TPLkb25H593hnObAB5WaiHB",
    stripeMonthlyPriceId: "price_1TPLkb25H593hnObuLNC7kEz",
    stripeYearlyPriceId: "price_1TPLkb25H593hnOb6U92Tq4k",
    isActive: true,
    sortOrder: 5,
  },

  // ---------------------------------------------------------------------------
  // Sector-tailored SmartCard presets (IDs 6–20). Each entry reuses the
  // SmartCard component but ships a sector-specific preset (see card-sectors.ts)
  // so the customer-facing copy/icons read native to the trade. Stripe price
  // IDs are populated by `npm run setup-stripe` once these become live SKUs.
  // ---------------------------------------------------------------------------
  {
    id: 6,
    slug: "avukat-hukuk",
    name: "Anwalt & Kanzlei",
    sectorHint: "lawyer",
    componentKey: "SmartCard",
    themeKey: "cinema",
    previewPath: "/images/templates/card-06.png",
    oneTimeCents: 12900,
    monthlyCents: 700,
    yearlyCents: 5900,
    stripeOneTimePriceId: "price_1TQCko25H593hnObiEXja3cd",
    stripeMonthlyPriceId: "price_1TQCkp25H593hnObJzi7IuBx",
    stripeYearlyPriceId: "price_1TQCkp25H593hnObxBk5EL2T",
    isActive: true,
    sortOrder: 6,
  },
  {
    id: 7,
    slug: "fotograf-kreatif",
    name: "Fotografie & Kreativ",
    sectorHint: "creator",
    componentKey: "SmartCard",
    themeKey: "editorial",
    previewPath: "/images/templates/card-07.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    stripeOneTimePriceId: "price_1TQCkq25H593hnObfKAsn6ab",
    stripeMonthlyPriceId: "price_1TQCkq25H593hnObArGlInUU",
    stripeYearlyPriceId: "price_1TQCkq25H593hnObRqBI275I",
    isActive: true,
    sortOrder: 7,
  },
  {
    id: 8,
    slug: "doktor-klinik",
    name: "Arzt & Klinik",
    sectorHint: "clinic",
    componentKey: "SmartCard",
    themeKey: "editorial",
    previewPath: "/images/templates/card-08.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    stripeOneTimePriceId: "price_1TQCkr25H593hnObcKA69AzJ",
    stripeMonthlyPriceId: "price_1TQCkr25H593hnObDFkAwRiC",
    stripeYearlyPriceId: "price_1TQCks25H593hnOb5jdKOyHZ",
    isActive: true,
    sortOrder: 8,
  },
  {
    id: 9,
    slug: "fitness-trainer",
    name: "Fitness & Personal Training",
    sectorHint: "fitness",
    componentKey: "SmartCard",
    themeKey: "aurora",
    previewPath: "/images/templates/card-09.png",
    oneTimeCents: 7900,
    monthlyCents: 500,
    yearlyCents: 3900,
    stripeOneTimePriceId: "price_1TQCkt25H593hnObwXLeNaWf",
    stripeMonthlyPriceId: "price_1TQCkt25H593hnObrKTFeL96",
    stripeYearlyPriceId: "price_1TQCkt25H593hnObY2PMOEc7",
    isActive: true,
    sortOrder: 9,
  },
  {
    id: 10,
    slug: "dj-muzik",
    name: "DJ & Musik",
    sectorHint: "music",
    componentKey: "SmartCard",
    themeKey: "aurora",
    previewPath: "/images/templates/card-10.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    stripeOneTimePriceId: "price_1TQCku25H593hnObfaQu44rw",
    stripeMonthlyPriceId: "price_1TQCku25H593hnOb7aUEVBP3",
    stripeYearlyPriceId: "price_1TQCku25H593hnObxFlkUgCw",
    isActive: true,
    sortOrder: 10,
  },
  {
    id: 11,
    slug: "mimar-tasarim",
    name: "Architektur & Design",
    sectorHint: "architecture",
    componentKey: "SmartCard",
    themeKey: "editorial",
    previewPath: "/images/templates/card-11.png",
    oneTimeCents: 12900,
    monthlyCents: 700,
    yearlyCents: 5900,
    stripeOneTimePriceId: "price_1TQCkv25H593hnObzwNJ16rP",
    stripeMonthlyPriceId: "price_1TQCkv25H593hnOb5Adb6AOX",
    stripeYearlyPriceId: "price_1TQCkw25H593hnObpCVBGhGN",
    isActive: true,
    sortOrder: 11,
  },
  {
    id: 12,
    slug: "eticaret-butik",
    name: "E-Commerce & Boutique",
    sectorHint: "retail",
    componentKey: "SmartCard",
    themeKey: "aurora",
    previewPath: "/images/templates/card-12.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    stripeOneTimePriceId: "price_1TQCkw25H593hnObDZneJL2x",
    stripeMonthlyPriceId: "price_1TQCkx25H593hnOb6tQUsYud",
    stripeYearlyPriceId: "price_1TQCkx25H593hnOb4ecB4pYH",
    isActive: true,
    sortOrder: 12,
  },
  // ---------------------------------------------------------------------------
  // Phase 7.7 — id=13 is the new "Universal Pro" sector-agnostic v2 template.
  // (The previous legacy "Hotel & Hospitality" placeholder under id=13 was
  // never surfaced by the carousel — `legacy: true` filtered it out — so
  // promoting this slot to a real v2 template doesn't hide anything customers
  // could already buy. Stripe price IDs are placeholders until run-stripe.)
  //
  // ---------------------------------------------------------------------------
  // Phase 7 legacy entries (ids 14..20). Kept so any pre-existing CardOrder
  // row whose templateId is here still resolves to a label + billing record.
  // The carousel filters these out via `legacy: true`; SmartCard handles render.
  // ---------------------------------------------------------------------------
  {
    id: 13,
    slug: "universal-pro",
    name: "Universal Pro",
    sectorHint: "consultant",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-13.png",
    monthlyCents: 500,
    yearlyCents: 3900,
    oneTimeCents: 7900,
    isActive: true,
    sortOrder: 13,
  },
  // ---------------------------------------------------------------------------
  // Phase 7.8 — designer-team v2 templates promoted from legacy. Stripe price
  // IDs preserved (re-used for the new SKUs); name/sector/legacy adjusted to
  // reflect the new sector-specific designs the v2 registry now wires up.
  // ---------------------------------------------------------------------------
  {
    id: 14,
    slug: "trattoria",
    name: "Trattoria",
    sectorHint: "restaurant",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-14.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    stripeOneTimePriceId: "price_1TQCkz25H593hnObxNBuGryn",
    stripeMonthlyPriceId: "price_1TQCkz25H593hnObZD93zURb",
    stripeYearlyPriceId: "price_1TQCl025H593hnObjR85tF3A",
    isActive: true,
    sortOrder: 14,
  },
  {
    id: 15,
    slug: "boutique-hotel",
    name: "Boutique Hotel",
    sectorHint: "hospitality",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-15.png",
    oneTimeCents: 12900,
    monthlyCents: 700,
    yearlyCents: 5900,
    stripeOneTimePriceId: "price_1TQCl025H593hnObBKBIRdxI",
    stripeMonthlyPriceId: "price_1TQCl025H593hnObMjeJRuv2",
    stripeYearlyPriceId: "price_1TQCl125H593hnObO1l4ELQH",
    isActive: true,
    sortOrder: 15,
  },
  {
    id: 16,
    slug: "tech-startup",
    name: "Tech Startup",
    sectorHint: "tech",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-16.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    stripeOneTimePriceId: "price_1TQCl125H593hnObu26AAzHw",
    stripeMonthlyPriceId: "price_1TQCl225H593hnObMuchpegq",
    stripeYearlyPriceId: "price_1TQCl225H593hnOb79HRO35d",
    isActive: true,
    sortOrder: 16,
  },
  {
    id: 17,
    slug: "developer",
    name: "Developer",
    sectorHint: "tech",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-17.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    stripeOneTimePriceId: "price_1TQCl225H593hnObmevKBs9x",
    stripeMonthlyPriceId: "price_1TQCl325H593hnObCyJqEMB5",
    stripeYearlyPriceId: "price_1TQCl325H593hnObrHbt5rbh",
    isActive: true,
    sortOrder: 17,
  },
  {
    id: 18,
    slug: "yoga-studio",
    name: "Yoga Studio",
    sectorHint: "fitness",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-18.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    stripeOneTimePriceId: "price_1TQCl425H593hnObjDMOJ69q",
    stripeMonthlyPriceId: "price_1TQCl425H593hnObf504NEXe",
    stripeYearlyPriceId: "price_1TQCl425H593hnObhBvTqugn",
    isActive: true,
    sortOrder: 18,
  },
  {
    id: 19,
    slug: "personal-trainer",
    name: "Personal Trainer",
    sectorHint: "fitness",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-19.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    stripeOneTimePriceId: "price_1TQCl525H593hnObl2DslNta",
    stripeMonthlyPriceId: "price_1TQCl525H593hnObO56KdLOz",
    stripeYearlyPriceId: "price_1TQCl625H593hnObXBVOMCqm",
    isActive: true,
    sortOrder: 19,
  },
  {
    id: 20,
    slug: "music-producer",
    name: "Music Producer",
    sectorHint: "music",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-20.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    stripeOneTimePriceId: "price_1TQCl625H593hnObRa5iYL0r",
    stripeMonthlyPriceId: "price_1TQCl725H593hnOb5UwrmIpa",
    stripeYearlyPriceId: "price_1TQCl725H593hnObpVPgYQCx",
    isActive: true,
    sortOrder: 20,
  },
  {
    id: 21,
    slug: "wedding-planner",
    name: "Wedding Planner",
    sectorHint: "events",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-21.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 21,
  },
  // ---------------------------------------------------------------------------
  // Phase 7.10 Batch A — Dentist · Psychologist · Beauty (3 sectors × 3 styles)
  // Stripe price IDs left empty until `npm run setup-stripe` is re-run with
  // the new SKUs in scope.
  // ---------------------------------------------------------------------------
  {
    id: 22,
    slug: "dentist",
    name: "Dentist",
    sectorHint: "dentist",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-22.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 22,
  },
  {
    id: 23,
    slug: "dentist-pure",
    name: "Dentist — Pure",
    sectorHint: "dentist",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-23.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 23,
  },
  {
    id: 24,
    slug: "dentist-vivid",
    name: "Dentist — Vivid",
    sectorHint: "dentist",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-24.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 24,
  },
  {
    id: 25,
    slug: "psychologist",
    name: "Psychologist",
    sectorHint: "psychologist",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-25.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 25,
  },
  {
    id: 26,
    slug: "psychologist-pure",
    name: "Psychologist — Pure",
    sectorHint: "psychologist",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-26.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 26,
  },
  {
    id: 27,
    slug: "psychologist-vivid",
    name: "Psychologist — Vivid",
    sectorHint: "psychologist",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-27.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 27,
  },
  {
    id: 28,
    slug: "beauty-salon",
    name: "Beauty Salon",
    sectorHint: "beauty",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-28.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 28,
  },
  {
    id: 29,
    slug: "beauty-salon-noir",
    name: "Beauty Salon — Noir",
    sectorHint: "beauty",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-29.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 29,
  },
  {
    id: 30,
    slug: "beauty-salon-pure",
    name: "Beauty Salon — Pure",
    sectorHint: "beauty",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-30.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 30,
  },
  // ---------------------------------------------------------------------------
  // Phase 7.10 Batch B — Accounting · Software · Content Creator (3 sectors × 3 styles)
  // Stripe price IDs left empty until `npm run setup-stripe` is re-run with
  // the new SKUs in scope.
  // ---------------------------------------------------------------------------
  {
    id: 31,
    slug: "accounting",
    name: "Accounting",
    sectorHint: "accounting",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-31.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 31,
  },
  {
    id: 32,
    slug: "accounting-noir",
    name: "Accounting — Noir",
    sectorHint: "accounting",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-32.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 32,
  },
  {
    id: 33,
    slug: "accounting-pure",
    name: "Accounting — Pure",
    sectorHint: "accounting",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-33.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 33,
  },
  {
    id: 34,
    slug: "software-dev",
    name: "Software Dev",
    sectorHint: "software",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-34.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 34,
  },
  {
    id: 35,
    slug: "software-dev-pure",
    name: "Software Dev — Pure",
    sectorHint: "software",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-35.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 35,
  },
  {
    id: 36,
    slug: "software-dev-vivid",
    name: "Software Dev — Vivid",
    sectorHint: "software",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-36.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 36,
  },
  {
    id: 37,
    slug: "content-creator",
    name: "Content Creator",
    sectorHint: "content-creator",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-37.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 37,
  },
  {
    id: 38,
    slug: "content-creator-noir",
    name: "Content Creator — Noir",
    sectorHint: "content-creator",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-38.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 38,
  },
  {
    id: 39,
    slug: "content-creator-pure",
    name: "Content Creator — Pure",
    sectorHint: "content-creator",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-39.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 39,
  },
  // Phase 7.10 Batch C — Wellness · Events · Auto · Interior
  {
    id: 40,
    slug: "wellness-teacher",
    name: "Wellness Teacher",
    sectorHint: "wellness",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-40.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 40,
  },
  {
    id: 41,
    slug: "wellness-teacher-pure",
    name: "Wellness — Pure",
    sectorHint: "wellness",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-41.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 41,
  },
  {
    id: 42,
    slug: "wellness-teacher-vivid",
    name: "Wellness — Vivid",
    sectorHint: "wellness",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-42.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 42,
  },
  {
    id: 43,
    slug: "event-planner",
    name: "Event Planner",
    sectorHint: "eventPlanner",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-43.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 43,
  },
  {
    id: 44,
    slug: "event-planner-noir",
    name: "Event Planner — Noir",
    sectorHint: "eventPlanner",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-44.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 44,
  },
  {
    id: 45,
    slug: "event-planner-pure",
    name: "Event Planner — Pure",
    sectorHint: "eventPlanner",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-45.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 45,
  },
  {
    id: 46,
    slug: "auto-dealer",
    name: "Auto Dealer",
    sectorHint: "auto",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-46.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 46,
  },
  {
    id: 47,
    slug: "auto-dealer-pure",
    name: "Auto Dealer — Pure",
    sectorHint: "auto",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-47.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 47,
  },
  {
    id: 48,
    slug: "auto-dealer-vivid",
    name: "Auto Dealer — Vivid",
    sectorHint: "auto",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-48.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 48,
  },
  {
    id: 49,
    slug: "interior-design",
    name: "Interior Design",
    sectorHint: "interior",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-49.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 49,
  },
  {
    id: 50,
    slug: "interior-design-noir",
    name: "Interior — Noir",
    sectorHint: "interior",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-50.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 50,
  },
  {
    id: 51,
    slug: "interior-design-vivid",
    name: "Interior — Vivid",
    sectorHint: "interior",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-51.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 51,
  },
  // Phase 7.11 Batch D-1 — Real Estate + Legal style variants (ids 52-59)
  {
    id: 52,
    slug: "real-estate-noir",
    name: "Real Estate — Noir",
    sectorHint: "realEstate",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-52.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 52,
  },
  {
    id: 53,
    slug: "real-estate-pure",
    name: "Real Estate — Pure",
    sectorHint: "realEstate",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-53.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 53,
  },
  {
    id: 54,
    slug: "real-estate-vivid",
    name: "Real Estate — Vivid",
    sectorHint: "realEstate",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-54.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 54,
  },
  {
    id: 55,
    slug: "real-estate-stone",
    name: "Real Estate — Stone",
    sectorHint: "realEstate",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-55.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 55,
  },
  {
    id: 56,
    slug: "legal-counsel-noir",
    name: "Legal Counsel — Noir",
    sectorHint: "lawyer",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-56.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 56,
  },
  {
    id: 57,
    slug: "legal-counsel-pure",
    name: "Legal Counsel — Pure",
    sectorHint: "lawyer",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-57.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 57,
  },
  {
    id: 58,
    slug: "legal-counsel-vivid",
    name: "Legal Counsel — Vivid",
    sectorHint: "lawyer",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-58.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 58,
  },
  {
    id: 59,
    slug: "legal-counsel-stone",
    name: "Legal Counsel — Stone",
    sectorHint: "lawyer",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-59.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 59,
  },
  // Phase 7.11 Batch D-2 — Restaurant + Photographer style variants
  {
    id: 60,
    slug: "restaurant-noir",
    name: "Restaurant — Noir",
    sectorHint: "restaurant",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-60.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 60,
  },
  {
    id: 61,
    slug: "restaurant-pure",
    name: "Restaurant — Pure",
    sectorHint: "restaurant",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-61.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 61,
  },
  {
    id: 62,
    slug: "restaurant-vivid",
    name: "Restaurant — Vivid",
    sectorHint: "restaurant",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-62.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 62,
  },
  {
    id: 63,
    slug: "restaurant-stone",
    name: "Restaurant — Stone",
    sectorHint: "restaurant",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-63.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 63,
  },
  {
    id: 64,
    slug: "photographer-noir",
    name: "Photographer — Noir",
    sectorHint: "creator",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-64.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 64,
  },
  {
    id: 65,
    slug: "photographer-pure",
    name: "Photographer — Pure",
    sectorHint: "creator",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-65.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 65,
  },
  {
    id: 66,
    slug: "photographer-vivid",
    name: "Photographer — Vivid",
    sectorHint: "creator",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-66.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 66,
  },
  {
    id: 67,
    slug: "photographer-stone",
    name: "Photographer — Stone",
    sectorHint: "creator",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-67.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 67,
  },
  // Phase 7.11 Batch D-3 — Clinic + DJ style variants
  {
    id: 68,
    slug: "clinic-noir",
    name: "Clinic — Noir",
    sectorHint: "clinic",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-68.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 68,
  },
  {
    id: 69,
    slug: "clinic-pure",
    name: "Clinic — Pure",
    sectorHint: "clinic",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-69.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 69,
  },
  {
    id: 70,
    slug: "clinic-vivid",
    name: "Clinic — Vivid",
    sectorHint: "clinic",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-70.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 70,
  },
  {
    id: 71,
    slug: "clinic-stone",
    name: "Clinic — Stone",
    sectorHint: "clinic",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-71.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 71,
  },
  {
    id: 72,
    slug: "dj-noir",
    name: "DJ — Noir",
    sectorHint: "music",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-72.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 72,
  },
  {
    id: 73,
    slug: "dj-pure",
    name: "DJ — Pure",
    sectorHint: "music",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-73.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 73,
  },
  {
    id: 74,
    slug: "dj-vivid",
    name: "DJ — Vivid",
    sectorHint: "music",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-74.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 74,
  },
  {
    id: 75,
    slug: "dj-stone",
    name: "DJ — Stone",
    sectorHint: "music",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-75.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 75,
  },
  // Phase 7.11 Batch D-4 — Barber + E-commerce style variants (ids 76-83)
  {
    id: 76,
    slug: "barber-noir",
    name: "Barber — Noir",
    sectorHint: "salon",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-76.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 76,
  },
  {
    id: 77,
    slug: "barber-pure",
    name: "Barber — Pure",
    sectorHint: "salon",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-77.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 77,
  },
  {
    id: 78,
    slug: "barber-vivid",
    name: "Barber — Vivid",
    sectorHint: "salon",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-78.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 78,
  },
  {
    id: 79,
    slug: "barber-stone",
    name: "Barber — Stone",
    sectorHint: "salon",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-79.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 79,
  },
  {
    id: 80,
    slug: "ecommerce",
    name: "E-commerce",
    sectorHint: "retail",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-80.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 80,
  },
  {
    id: 81,
    slug: "ecommerce-noir",
    name: "E-commerce — Noir",
    sectorHint: "retail",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-81.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 81,
  },
  {
    id: 82,
    slug: "ecommerce-pure",
    name: "E-commerce — Pure",
    sectorHint: "retail",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-82.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 82,
  },
  {
    id: 83,
    slug: "ecommerce-vivid",
    name: "E-commerce — Vivid",
    sectorHint: "retail",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-83.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 83,
  },
  // Phase 7.11 Batch D-5 — Architect + Fitness style variants (ids 84-91)
  {
    id: 84,
    slug: "architect-noir",
    name: "Architect — Noir",
    sectorHint: "architecture",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-84.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 84,
  },
  {
    id: 85,
    slug: "architect-pure",
    name: "Architect — Pure",
    sectorHint: "architecture",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-85.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 85,
  },
  {
    id: 86,
    slug: "architect-vivid",
    name: "Architect — Vivid",
    sectorHint: "architecture",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-86.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 86,
  },
  {
    id: 87,
    slug: "architect-stone",
    name: "Architect — Stone",
    sectorHint: "architecture",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-87.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 87,
  },
  {
    id: 88,
    slug: "fitness-noir",
    name: "Fitness — Noir",
    sectorHint: "fitness",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-88.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 88,
  },
  {
    id: 89,
    slug: "fitness-pure",
    name: "Fitness — Pure",
    sectorHint: "fitness",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-89.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 89,
  },
  {
    id: 90,
    slug: "fitness-vivid",
    name: "Fitness — Vivid",
    sectorHint: "fitness",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-90.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 90,
  },
  {
    id: 91,
    slug: "fitness-stone",
    name: "Fitness — Stone",
    sectorHint: "fitness",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-91.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 91,
  },
  // Phase 7.12 Batch E-1 — Universal layout templates v11-v15 (ids 92-96)
  {
    id: 92,
    slug: "layout-noir-luxury",
    name: "Noir Luxury",
    sectorHint: "consultant",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-92.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 92,
  },
  {
    id: 93,
    slug: "layout-pure-swiss",
    name: "Pure Swiss",
    sectorHint: "consultant",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-93.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 93,
  },
  {
    id: 94,
    slug: "layout-vivid-bold",
    name: "Vivid Bold",
    sectorHint: "consultant",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-94.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 94,
  },
  {
    id: 95,
    slug: "layout-editorial",
    name: "Editorial",
    sectorHint: "consultant",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-95.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 95,
  },
  {
    id: 96,
    slug: "layout-split-screen",
    name: "Split Screen",
    sectorHint: "consultant",
    componentKey: "SmartCard",
    previewPath: "/images/templates/card-96.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 96,
  },
  // ---------------------------------------------------------------------------
  // M3 — Linktree (id 100). Carrd-comparison amendment: a "link in bio"
  // creator template. Renders a vertical stack of full-width buttons (driven
  // by `customButtons[]` in cardData) instead of the standard contact-info
  // card surface. Falls back to SmartCard since no v2 component is wired —
  // the layoutKey "accordion" hint flows through to the renderer / preview
  // generator. Customers using this template typically populate avatar +
  // name + bio + 6 buttons + socials.
  // ---------------------------------------------------------------------------
  {
    id: 100,
    slug: "linktree",
    name: "Linktree",
    sectorHint: "creator",
    componentKey: "SmartCard",
    themeKey: "editorial",
    previewPath: "/images/templates/card-100.png",
    oneTimeCents: 9900,
    monthlyCents: 600,
    yearlyCents: 4900,
    isActive: true,
    sortOrder: 100,
  },
];

export function getTemplateById(id: number): CardTemplateDef | undefined {
  return cardTemplates.find((t) => t.id === id);
}

export function getActiveTemplates(): CardTemplateDef[] {
  return cardTemplates
    .filter((t) => t.isActive)
    .sort((a, b) => a.sortOrder - b.sortOrder);
}

/**
 * Format a cent amount as a localized euro string (e.g. 4900 -> "€49,00" in de).
 */
export function formatEuro(cents: number, locale = "de-DE"): string {
  return new Intl.NumberFormat(locale, {
    style: "currency",
    currency: "EUR",
    maximumFractionDigits: 0,
  }).format(cents / 100);
}
