import type { OpsoLocale } from "@/lib/opso-web/contracts";

const en = {
  eventOnly: "Event access (manage in the app)",
  eyebrow: "YOUR OPSO WORKSPACE", title: "One account. Your cards, everywhere.", intro: "Create your OpSo card here and continue in the mobile app with the same email address.",
  signIn: "Sign in to OpSo", email: "Email address", emailHelp: "Use the email address of your OpSo mobile account. We will send a six-digit sign-in code.", sendCode: "Send sign-in code", code: "Six-digit code", verify: "Sign in", changeEmail: "Use another email", codeSent: "Check your inbox. Your code is valid for 15 minutes.",
  loading: "Loading your workspace…", working: "Please wait…", logout: "Sign out", loggedOut: "You are signed out.", logoutPartial: "You are signed out of this browser. The server could not confirm session revocation. You can end that session in the app's account settings.",
  cards: "Your OpSo cards", empty: "Your first introduction starts here", emptyHelp: "Free includes one card. Choose a layout, add your details, then review and publish.", create: "Create a draft", edit: "Edit profile", saved: "Draft saved. Review it before publishing.", created: "Your draft is ready. It also belongs to your OpSo mobile account.", published: "Your card is published. You can share its link now.",
  name: "Full name", role: "Role", company: "Company", phone: "Phone", location: "Location", language: "Card language", slug: "Your card link", slugHelp: "3–64 lowercase letters, numbers or hyphens. Start and end with a letter or number.", checkSlug: "Check link", slugAvailable: "This link is available. It is reserved when you create the draft.", slugTaken: "This link is already in use. Choose another.",
  layout: "Choose your layout", layoutHelp: "These layouts are ready for a profile card. Build websites and additional pages in the mobile studio.", privacy: "Privacy and contact details", discoverable: "Include my card in discovery", indexable: "Allow search engines to index the card", showEmail: "Show email on the public card", showPhone: "Show phone on the public card", visibility: "Visibility", public: "Public", unlisted: "Only people with the link", private: "Private", visibilityHelp: "Reducing visibility applies immediately when you save. Other changes become public when you publish.",
  save: "Save draft", publish: "Publish saved draft", savedFirst: "Save your changes before publishing.", profilePreview: "Live profile preview", previewHelp: "This preview shows your profile details and contact visibility. Open your published card for the complete layout. Existing pages, media and sections are preserved.", serverPreview: "Check public profile", verifiedPreview: "Profile checked against the OpSo renderer data.", terms: "I accept the current community rules and content terms", readTerms: "Read the terms", openCard: "Open published card", copied: "Link copied", copyLink: "Copy link", draft: "Draft", publishedStatus: "Published", back: "All cards", refresh: "Reload saved version", conflictHelp: "Another device changed this card. Your text is still here. Copy any changes you need, then reload the saved version before trying again.",
  companion: "Continue in the OpSo app", companionHelp: "Sign in with this same email address to see your OpSo cards. The app has the full website editor, scanning and NFC tools.", availability: "App availability", legacy: "Cards from the older OpSolid website editor remain in its existing dashboard. They are not automatically transferred into OpSo.", legacyLink: "Open previous dashboard", unavailable: "Web sign-in is not available yet. Your existing OpSo mobile account and cards are unchanged. Check app availability below.",
  error: "The request could not be completed. Your entered details are still here. Please try again.", authError: "Your session has expired. Sign in again to continue.", invalidCode: "That code could not be verified. Check the code or request a new one.", limitError: "Your account has reached its card limit. Open an existing card to edit it.", rateError: "Too many requests. Please wait before trying again.", termsError: "Please review and accept the current terms before publishing.", readinessError: "This card has unfinished content. Complete its pages and sections in the mobile studio before publishing.",
} as const;
type Copy = { [K in keyof typeof en]: string };
const de: Copy = {
  eventOnly: "Event-Zugriff (in der App verwalten)",
  eyebrow: "DEIN OPSO ARBEITSBEREICH", title: "Ein Konto. Deine Karten, überall.", intro: "Erstelle deine OpSo Karte hier und arbeite in der mobilen App mit derselben E-Mail-Adresse weiter.",
  signIn: "Bei OpSo anmelden", email: "E-Mail-Adresse", emailHelp: "Nutze die E-Mail-Adresse deines OpSo App-Kontos. Du erhältst einen sechsstelligen Anmeldecode.", sendCode: "Anmeldecode senden", code: "Sechsstelliger Code", verify: "Anmelden", changeEmail: "Andere E-Mail verwenden", codeSent: "Prüfe dein Postfach. Dein Code ist 15 Minuten gültig.",
  loading: "Dein Arbeitsbereich wird geladen…", working: "Bitte warten…", logout: "Abmelden", loggedOut: "Du bist abgemeldet.", logoutPartial: "Du bist in diesem Browser abgemeldet. Der Server konnte das Beenden der Sitzung nicht bestätigen. Du kannst sie in den Kontoeinstellungen der App beenden.",
  cards: "Deine OpSo Karten", empty: "Dein erster Eindruck beginnt hier", emptyHelp: "Free enthält eine Karte. Wähle ein Layout, ergänze deine Angaben und prüfe die Karte vor der Veröffentlichung.", create: "Entwurf erstellen", edit: "Profil bearbeiten", saved: "Entwurf gespeichert. Prüfe ihn vor der Veröffentlichung.", created: "Dein Entwurf ist bereit. Er gehört auch zu deinem OpSo App-Konto.", published: "Deine Karte ist veröffentlicht. Du kannst den Link jetzt teilen.",
  name: "Vollständiger Name", role: "Position", company: "Unternehmen", phone: "Telefon", location: "Standort", language: "Kartensprache", slug: "Dein Kartenlink", slugHelp: "3–64 Kleinbuchstaben, Ziffern oder Bindestriche. Anfang und Ende müssen Buchstaben oder Ziffern sein.", checkSlug: "Link prüfen", slugAvailable: "Dieser Link ist verfügbar. Er wird beim Erstellen des Entwurfs reserviert.", slugTaken: "Dieser Link ist bereits vergeben. Wähle einen anderen.",
  layout: "Wähle dein Layout", layoutHelp: "Diese Layouts sind für eine Profilkarte vorbereitet. Websites und zusätzliche Seiten gestaltest du im mobilen Studio.", privacy: "Datenschutz und Kontaktdaten", discoverable: "Meine Karte in der Entdecken-Ansicht anzeigen", indexable: "Suchmaschinen dürfen die Karte indexieren", showEmail: "E-Mail auf der öffentlichen Karte anzeigen", showPhone: "Telefon auf der öffentlichen Karte anzeigen", visibility: "Sichtbarkeit", public: "Öffentlich", unlisted: "Nur Personen mit dem Link", private: "Privat", visibilityHelp: "Eine Einschränkung der Sichtbarkeit gilt sofort nach dem Speichern. Andere Änderungen werden erst mit der Veröffentlichung öffentlich.",
  save: "Entwurf speichern", publish: "Gespeicherten Entwurf veröffentlichen", savedFirst: "Speichere deine Änderungen vor der Veröffentlichung.", profilePreview: "Live-Profilvorschau", previewHelp: "Die Vorschau zeigt Profildaten und sichtbare Kontaktdaten. Öffne deine veröffentlichte Karte für das vollständige Layout. Vorhandene Seiten, Medien und Abschnitte bleiben erhalten.", serverPreview: "Öffentliches Profil prüfen", verifiedPreview: "Profil anhand der OpSo Darstellungsdaten geprüft.", terms: "Ich akzeptiere die aktuellen Community-Regeln und Inhaltsbedingungen", readTerms: "Bedingungen lesen", openCard: "Veröffentlichte Karte öffnen", copied: "Link kopiert", copyLink: "Link kopieren", draft: "Entwurf", publishedStatus: "Veröffentlicht", back: "Alle Karten", refresh: "Gespeicherte Version laden", conflictHelp: "Diese Karte wurde auf einem anderen Gerät geändert. Dein Text bleibt hier erhalten. Kopiere benötigte Änderungen und lade dann die gespeicherte Version, bevor du es erneut versuchst.",
  companion: "In der OpSo App weiterarbeiten", companionHelp: "Melde dich mit derselben E-Mail-Adresse an, um deine OpSo Karten zu sehen. Die App bietet den vollständigen Website-Editor, Scannen und NFC-Werkzeuge.", availability: "Verfügbarkeit der App", legacy: "Karten aus dem bisherigen OpSolid Website-Editor bleiben im bestehenden Dashboard. Sie werden nicht automatisch nach OpSo übertragen.", legacyLink: "Bisheriges Dashboard öffnen", unavailable: "Die Web-Anmeldung ist noch nicht verfügbar. Dein bestehendes OpSo App-Konto und deine Karten bleiben erhalten. Informationen zur App findest du unten.",
  error: "Die Anfrage konnte nicht abgeschlossen werden. Deine Eingaben bleiben erhalten. Bitte versuche es erneut.", authError: "Deine Sitzung ist abgelaufen. Melde dich erneut an.", invalidCode: "Der Code konnte nicht bestätigt werden. Prüfe ihn oder fordere einen neuen an.", limitError: "Dein Konto hat sein Kartenlimit erreicht. Öffne eine vorhandene Karte zum Bearbeiten.", rateError: "Zu viele Anfragen. Bitte warte vor dem nächsten Versuch.", termsError: "Bitte lies und akzeptiere die aktuellen Bedingungen vor der Veröffentlichung.", readinessError: "Diese Karte enthält noch unvollständige Inhalte. Ergänze Seiten und Abschnitte im mobilen Studio vor der Veröffentlichung.",
};
const tr: Copy = {
  eventOnly: "Etkinlik erişimi (uygulamada yönet)",
  eyebrow: "OPSO ÇALIŞMA ALANIN", title: "Tek hesap. Kartların her yerde.", intro: "OpSo kartını burada oluştur, mobil uygulamada aynı e-posta adresiyle devam et.",
  signIn: "OpSo hesabına giriş yap", email: "E-posta adresi", emailHelp: "OpSo mobil hesabının e-posta adresini kullan. Sana altı haneli bir giriş kodu göndereceğiz.", sendCode: "Giriş kodu gönder", code: "Altı haneli kod", verify: "Giriş yap", changeEmail: "Başka e-posta kullan", codeSent: "Gelen kutunu kontrol et. Kodun 15 dakika geçerlidir.",
  loading: "Çalışma alanın yükleniyor…", working: "Lütfen bekle…", logout: "Çıkış yap", loggedOut: "Çıkış yaptın.", logoutPartial: "Bu tarayıcıdan çıkış yaptın. Sunucu oturumun sonlandırıldığını doğrulayamadı. Uygulamanın hesap ayarlarından bu oturumu kapatabilirsin.",
  cards: "OpSo kartların", empty: "İlk izlenimin burada başlıyor", emptyHelp: "Free bir kart içerir. Bir tasarım seç, bilgilerini ekle, ardından kontrol edip yayınla.", create: "Taslak oluştur", edit: "Profili düzenle", saved: "Taslak kaydedildi. Yayınlamadan önce kontrol et.", created: "Taslağın hazır. OpSo mobil hesabında da aynı kart yer alır.", published: "Kartın yayınlandı. Bağlantıyı artık paylaşabilirsin.",
  name: "Ad soyad", role: "Unvan", company: "Şirket", phone: "Telefon", location: "Konum", language: "Kart dili", slug: "Kart bağlantın", slugHelp: "3–64 küçük harf, rakam veya kısa çizgi. İlk ve son karakter harf veya rakam olmalı.", checkSlug: "Bağlantıyı kontrol et", slugAvailable: "Bu bağlantı kullanılabilir. Taslak oluşturulduğunda ayrılır.", slugTaken: "Bu bağlantı kullanılıyor. Başka bir bağlantı seç.",
  layout: "Tasarımını seç", layoutHelp: "Bu tasarımlar profil kartı için hazırdır. Web sitelerini ve ek sayfaları mobil stüdyoda oluşturabilirsin.", privacy: "Gizlilik ve iletişim bilgileri", discoverable: "Kartımı keşfet bölümünde göster", indexable: "Arama motorlarının kartı dizine eklemesine izin ver", showEmail: "Herkese açık kartta e-postayı göster", showPhone: "Herkese açık kartta telefonu göster", visibility: "Görünürlük", public: "Herkese açık", unlisted: "Yalnızca bağlantıyı bilenler", private: "Özel", visibilityHelp: "Görünürlüğü kısıtlamak kaydettiğinde hemen uygulanır. Diğer değişiklikler yayınladığında herkese açılır.",
  save: "Taslağı kaydet", publish: "Kaydedilmiş taslağı yayınla", savedFirst: "Yayınlamadan önce değişikliklerini kaydet.", profilePreview: "Canlı profil önizlemesi", previewHelp: "Bu önizleme profilini ve görünür iletişim bilgilerini gösterir. Tam tasarım için yayınlanmış kartını aç. Mevcut sayfalar, medya ve bölümler korunur.", serverPreview: "Herkese açık profili kontrol et", verifiedPreview: "Profil, OpSo görüntüleme verileriyle kontrol edildi.", terms: "Güncel topluluk kurallarını ve içerik koşullarını kabul ediyorum", readTerms: "Koşulları oku", openCard: "Yayınlanmış kartı aç", copied: "Bağlantı kopyalandı", copyLink: "Bağlantıyı kopyala", draft: "Taslak", publishedStatus: "Yayında", back: "Tüm kartlar", refresh: "Kaydedilmiş sürümü yükle", conflictHelp: "Bu kart başka bir cihazda değiştirildi. Metnin burada korunuyor. Gerekli değişiklikleri kopyala, ardından tekrar denemeden önce kaydedilmiş sürümü yükle.",
  companion: "OpSo uygulamasında devam et", companionHelp: "OpSo kartlarını görmek için aynı e-posta adresiyle giriş yap. Uygulamada tam web sitesi editörü, tarama ve NFC araçları bulunur.", availability: "Uygulamaya erişim", legacy: "Eski OpSolid web editöründe oluşturulan kartlar mevcut panelinde kalır. OpSo hesabına otomatik aktarılmaz.", legacyLink: "Önceki paneli aç", unavailable: "Web üzerinden giriş henüz kullanıma açık değil. Mevcut OpSo mobil hesabın ve kartların korunuyor. Uygulamaya erişim bilgileri aşağıda.",
  error: "İşlem tamamlanamadı. Girdiğin bilgiler burada duruyor. Lütfen tekrar dene.", authError: "Oturumunun süresi doldu. Devam etmek için tekrar giriş yap.", invalidCode: "Kod doğrulanamadı. Kodu kontrol et veya yenisini iste.", limitError: "Hesabının kart sınırına ulaşıldı. Düzenlemek için mevcut kartlarından birini aç.", rateError: "Çok fazla istek gönderildi. Tekrar denemeden önce biraz bekle.", termsError: "Yayınlamadan önce güncel koşulları okuyup kabul et.", readinessError: "Bu kartta tamamlanmamış içerik var. Yayınlamadan önce mobil stüdyoda sayfaları ve bölümleri tamamla.",
};
export function getOpsoAccountCopy(locale: OpsoLocale): Copy { return { en, de, tr }[locale]; }
