// =============================================================================
// GENERATOR — scripts/gen-labels-registry.ts
//
// Emits src/components/cards/templates/v2/labelsRegistry.ts: a map from each
// template's registry `key` to its exported `COPY` table, via namespace
// imports so the editor reads the SAME copy the template renders (no drift).
//
// Re-run after adding a template (or changing a key). NOT wired into build.
//   npx tsx scripts/gen-labels-registry.ts
// =============================================================================

import * as fs from "fs";
import * as path from "path";

const V2_DIR = path.join(__dirname, "..", "src", "components", "cards", "templates", "v2");
const OUT = path.join(V2_DIR, "labelsRegistry.ts");

// RealEstate's entry lives inline in registry.ts, so its file has no *Entry.
const KEY_OVERRIDES: Record<string, string> = { "RealEstate.tsx": "real-estate" };

interface Row {
  key: string;
  importName: string;
  module: string;
}
const rows: Row[] = [];

for (const file of fs.readdirSync(V2_DIR).sort()) {
  if (!file.endsWith(".tsx")) continue;
  const src = fs.readFileSync(path.join(V2_DIR, file), "utf8");
  if (!/export const COPY\b/.test(src)) continue;

  let key = KEY_OVERRIDES[file];
  if (!key) {
    // Matches `xEntry = {`, `xEntry: TemplateRegistryEntry = {`, and
    // `xEntry: Omit<TemplateRegistryEntry, "Component"> = {` — then the first
    // `key: "..."` (the registry key sits at the top of the entry object).
    const m = src.match(/\w+Entry\s*(?::\s*[^=]+)?=\s*\{[\s\S]*?\bkey:\s*"([^"]+)"/);
    if (!m) {
      console.error(`WARN: ${file} exports COPY but no entry key found — skipped`);
      continue;
    }
    key = m[1];
  }

  const base = path.basename(file, ".tsx");
  rows.push({ key, importName: `M_${base}`, module: `./${base}` });
}

rows.sort((a, b) => a.key.localeCompare(b.key));

const header = `// =============================================================================
// AUTO-GENERATED by scripts/gen-labels-registry.ts — DO NOT EDIT BY HAND.
// Re-run the generator after adding a template or changing a registry key.
//
// Maps each template's registry \`key\` to its exported \`COPY\` table so the
// order form / live editor can list a template's editable section-label keys
// and their localized defaults (placeholder text). Reading the live COPY keeps
// the editor in lockstep with what each template actually renders.
//
// Server-safe (no "use client"): mirrors registry.ts, which already reads plain
// objects exported from the client template modules.
// =============================================================================

`;

const importLines = rows.map((r) => `import * as ${r.importName} from "${r.module}";`).join("\n");

const types = `

/** Editable section-label keys -> default text, for one locale. */
export type LabelDefaults = Record<string, string>;
/** Locale -> LabelDefaults. The template COPY tables satisfy this at runtime;
 *  the cast bridges the interface (no index signature) -> Record gap. */
export type LabelCopyTable = Partial<
  Record<"de" | "en" | "tr" | "es" | "it" | "fr" | "ar", LabelDefaults>
>;

const tbl = (copy: unknown): LabelCopyTable => copy as LabelCopyTable;
`;

const mapLines = rows.map((r) => `  ${JSON.stringify(r.key)}: tbl(${r.importName}.COPY),`).join("\n");

const body = `

/** template registry key -> its localized label copy table. */
export const labelsRegistry: Record<string, LabelCopyTable> = {
${mapLines}
};

/**
 * The editable label keys + localized default text for a template key in the
 * given locale. Returns [] for unknown templates (the editor then renders no
 * label group). Falls back to the German defaults when the locale is missing.
 */
export function getEditableLabels(
  templateKey: string | undefined | null,
  locale: string,
): Array<{ key: string; default: string }> {
  if (!templateKey) return [];
  const table = labelsRegistry[templateKey];
  if (!table) return [];
  const defaults = (table as Record<string, LabelDefaults | undefined>)[locale] ?? table.de;
  if (!defaults) return [];
  return Object.entries(defaults).map(([key, value]) => ({ key, default: value }));
}
`;

fs.writeFileSync(OUT, header + importLines + types + body, "utf8");
console.log(`gen-labels-registry: wrote ${rows.length} templates to ${path.relative(process.cwd(), OUT)}`);
